const Settings = {
  api: {
    // getFilterViewLists: "/hotelpgoosmaint/getFilterViewLists.action",
    getRegions: "/reportingregionlist/getRegions.action",
    getCountries: "/countrylist/getCountries.action",
    getStates: "/statelist/getStates.action",
    getCities: "/citylist/getCities.action",
    getHotelPGOOSList: "/hotelpgoosmaintlist/getHotelPGOOSList.action",
    getAccountSegment: "/accountsegmentlist/getAccountSegment.action",
    getAccountLists: "/accounts/getAccountLists.action",
    getEdieProfiles: "/edieprofilelist/getEdieProfiles.action",
    getAccountSubsets: "/accountsubsetlist/getAccountSubsets.action",
    getEdieHotelProfiles: "/ediehotelprofilelist/getEdieHotelProfiles.action",
    getRateProgramList: "/rateprogram/getRateProgramList.action",
    getReportTypes: "/pricingreportview/getPricingReportViewFilterLists",
    getAccAerType: "/accountaertype/getAccAerType.action",
    getReportdetail: "/reports/reportdetail.action",
    getDueDate :"/duedatelist/getDueDate",
  },
  quickSelect: "Quick Select",
  quickSelectObject: {
    label: "Hotel List:",
    textareaId: "hotellist2",
    row: 10,
    cols: 100,
    textareaName: "hoteldlist2",
  },
  alertMessage: "Alert Message",
  okClose: "OK - Close Message Box",
  marshacodeSeparatedByComma: "Please enter only marshacodes seperated by a ,",
  enter200Hotels: "Please enter only 200 hotels at a time.",
  DateFormat: "Date Format",
  dateFormatId: "filterValues.exceldateformat",
  highlightedOnly: "filterValues.highlightedOnly",
  Y: "Y",
  N: "N",
  runReportHighlight: "Run report for highlighted hotels only",
};
export default Settings;
