// Generated by https://quicktype.io

export interface Scptsetup {
  brandName: string;
  updateSCPTPricing: null;
  isLocked: string;
  lastUpdatedUser: string;
  setuptab_last_updated: string;
  checkUpdateSCPT: null;
  scptSetUpGenInfo: ScptSetUpGenInfo;
  scptSetUpWtdRetailRate: ScptSetUpWtdRetailRate;
  scptSetUpAmenities: ScptSetUpAmenities;
  scptSetUpThresholds: ScptSetUpThresholds;
  scptSetUpBudgetAndForecastData: { [key: string]: number | null };
  scptSetUpRetailRate: ScptSetUpRetailRate[];
  seasonList: SeasonList[];
}

export interface ScptSetUpAmenities {
  brkf_type: string;
  internet_type: string;
  transport: string;
  parking: string;
  brkf_fcost: number;
  internet_fcost: number;
  transport_fcost: number;
  parking_fcost: number;
  vatpercentroomrate: number;
  vatpercentrfoodandbeverage: null;
  histPrevYearVat: null;
  histTwoPrevYearVat: null;
  breakfastList: BreakfastList[];
  internetList: InternetList[];
}

export interface BreakfastList {
  scpt_breaktypeid: number;
  breakfastname: string;
}

export interface InternetList {
  scpt_internettypeid: number;
  internetname: string;
}

export interface ScptSetUpGenInfo {
  hotelid: number;
  period: number;
  rpp_setup_1: string;
  rpp_setup_2: string;
  rpp_setup_3: string;
  rpp_setup_total: string;
  tier_price_tier1: null;
  tier_price_tier2: null;
  tier_price_tier3: null;
  tier_price_tier4: null;
  tier_price_total: null;
  hotel_vat: string;
  show_yoy_comp: string;
}

export interface ScptSetUpRetailRate {
  seasonid: number;
  prev_ret_rate: number;
  curr_ret_rate: number;
}

export interface ScptSetUpThresholds {
  thrs_rmnt_low: number;
  thrs_rmnt_mid: number;
  thrs_perct_rtl_low: number;
  thrs_perct_rtl_mid: number;
  thrs_curry_rtl_low: number;
  thrs_curry_rtl_mid: number;
  thrs_percentage: string;
}

export interface ScptSetUpWtdRetailRate {
  yoy_retailrate_chg: number;
  wtd_prev_retail_rate: number;
  wtd_retail_rate: number;
}

export interface SeasonList {
  rfpseasonid: null;
  hotelrfpid: null;
  seasonid: number;
  startdate: string;
  enddate: string;
  roomNights: number;
}
