import React, { useEffect, useState } from "react";
import styles from "./catering.css";
import CateringAPI from "../service/cateringAPI";
import Settings from "../static/Settings";
import { Layout } from "../../../routing/Layout";
import SalesAdministartionContext, {
  SalesAdministartionContextProvider,
} from "../../../context/salesAdministartionContextProvider";
import Utils from "../../../../../common/utils/Utils";
//import SappUtils from "../../../shared/Utils";
import { useLocation } from "react-router-dom";
import CateringContext, {
  CateringContextProvider,
} from "../context/cateringContext";
import CModal from "../../../../../common/components/CModal";
import screenLoader from "../../../../../common/assets/img/screenloader.gif";

let contextType = null;
let parentContextType = null;

const Catering = (props) => {
  const urlParms = useLocation().search;
  const RecID = new URLSearchParams(urlParms).get("accountrecid");
  const yearSel = new URLSearchParams(urlParms).get("year");
  const accname = new URLSearchParams(urlParms).get("accountName");
  const [lastUpdateDateValue, setlastUpdateDateValue] = useState("");
  const [lastUpdateDateValueonUpdate, setlastUpdateDateValueonUpdate] =
    useState("");
  useEffect(() => {
    contextType.state.showScreenLoader = true;
    CateringAPI.getData(RecID, yearSel, accname).then((data) => {
      contextType.state.showScreenLoader = false;
      contextType.setLoadingData(data);
      setlastUpdateDateValue(data.lastUpdate);
    });
    contextType.setInitialUserData();
    return () => {
      UpdateCateringData();
    };
  }, []);

  const UpdateCateringData = () => {
    const validatedUserValidations = contextType.checkUpdateValidation();
    if (validatedUserValidations) {
      contextType.updateValue(RecID, yearSel, accname);
      if (contextType?.state?.lastUpdateDate) {
        setlastUpdateDateValueonUpdate(contextType?.state?.lastUpdateDate);
      }
    }
  };

  const handleInputValidationCatering = (e, field) => {
    const updatePrimaryListCatering = contextType.state.catering;
    updatePrimaryListCatering[field] = e.target.value;
    contextType.setData(updatePrimaryListCatering);
    contextType.mandatoryCheck();
  };

  const handleInputValidationRevenue = (e, field) => {
    const updatePrimaryListRevenue = contextType.state.revStreamDescription;
    updatePrimaryListRevenue[field] = e.target.value;
    contextType.setData(updatePrimaryListRevenue);
    contextType.mandatoryCheck();
  };

  const handlePercentageInputValidation = (e, field) => {
    const updatePrimaryListPercentage = contextType.state.catering;
    updatePrimaryListPercentage[field] = e.target.value;
    contextType.setData(updatePrimaryListPercentage);
    const validateData = contextType.numberRangeValidation();
    if (validateData) {
      contextType.setData(field);
    }
    contextType.mandatoryCheck();
  };

  const handleTabInputValidation = (e, fieldName) => {
    if (e.target.value !== "") {
      if (e.target.value > 100 || e.target.value < 0) {
        contextType.setValidationFunc(
          Settings.CateringDetails.alertRangeMessage
        );
      } else {
        const updatedFieldVal = contextType.state.catering;
        updatedFieldVal[fieldName] = e.target.value;
        contextType.setData(updatedFieldVal);
      }
    }
    contextType.mandatoryCheck();
  };

  const handleDropdownSelection = (e, fieldName) => {
    const updatedField = contextType.state.catering;
    if (e.target.value != "") {
      updatedField[fieldName] = e.target.value;
    } else {
      updatedField[fieldName] = null;
    }
    contextType.setData(updatedField);
    contextType.mandatoryCheck();
  };

  const handleTextAreaInputValidation = (e, field) => {
    const updatePrimaryListTextArea = contextType.state.revStreamDescription;
    updatePrimaryListTextArea[field] = e.target.value;
    const mandatoryTextAreaCheck = contextType.mandatoryTextFieldInputCheck();
    if (mandatoryTextAreaCheck) {
      contextType.setData(updatePrimaryListTextArea);
    }
    contextType.mandatoryCheck();
  };

  const handleCateringTextAreaInputValidation = (e, field) => {
    const updatePrimaryListCateringTextArea = contextType.state.catering;
    updatePrimaryListCateringTextArea[field] = e.target.value;
    const mandatoryCateringTextAreaCheck =
      contextType.mandatoryTextFieldInputCheck();
    if (mandatoryCateringTextAreaCheck) {
      contextType.setData(updatePrimaryListCateringTextArea);
    }
    contextType.mandatoryCheck();
  };

  return (
    <SalesAdministartionContext.Consumer>
      {(SalesAdministartionContext) => {
        parentContextType = SalesAdministartionContext;
        return (
          <Layout
            IsCateringDataUpdate={UpdateCateringData}
            getlastUpdateDate={lastUpdateDateValue}
            onUpdateValue={lastUpdateDateValueonUpdate}
          >
            <CateringContextProvider>
              <CateringContext.Consumer>
                {(cateringInfoContext) => {
                  contextType = cateringInfoContext;

                  return (
                    <React.Fragment>
                      <CModal
                        title={Settings.CateringDetails.alertMessage}
                        onClose={contextType.ShowValidateModel}
                        show={contextType.state.validateModal}
                        xPosition={-100}
                        yPosition={-120}
                        closeImgTitle={Settings.CateringDetails.closeTitle}
                        class="customModal"
                        overlayHeight={Math.max(
                          document.body.scrollHeight,
                          document.body.offsetHeight,
                          document.documentElement.clientHeight,
                          document.documentElement.scrollHeight,
                          document.documentElement.offsetHeight
                        )}
                        overlayTopPosition={"-79px"}
                      >
                        <div className={styles.cateringAlert}>
                          {contextType.state.message}
                        </div>
                      </CModal>
                      {contextType.state.showScreenLoader ? (
                        <img
                          style={{
                            position: "absolute",
                            top: "55%",
                            left: "45%",
                          }}
                          src={screenLoader}
                        />
                      ) : (
                        <div className={styles.pageLoader}>
                          <table className={styles.zero_Height}>
                            <tbody>
                              <tr>
                                <td>
                                  <tr>
                                    <td colSpan={2}>&nbsp;</td>
                                  </tr>
                                  <tr>
                                    <td>
                                      <p>
                                        <table className={styles.sectionWidth}>
                                          <tr>
                                            <td
                                              colSpan={2}
                                              className={
                                                styles.instructionHeader
                                              }
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .businessAndSpend
                                              }
                                            </td>
                                          </tr>
                                          <tr>
                                            <td width="270">&nbsp;</td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            ></td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                              title={
                                                Settings.CateringDetails
                                                  .businessAndSpendTitle
                                              }
                                              width="270"
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .estSpend
                                              }
                                            </td>
                                            <td className={styles.Field_Name}>
                                              <input
                                                tabIndex={1}
                                                type="text"
                                                name={
                                                  contextType.state.catering
                                                    .est_ttl_spnd
                                                }
                                                id={
                                                  contextType.state.catering
                                                    .est_ttl_spnd
                                                }
                                                value={
                                                  contextType.state.catering
                                                    .est_ttl_spnd
                                                }
                                                size={20}
                                                maxLength={12}
                                                onKeyPress={
                                                  Utils.NumberOnly_onkeypress
                                                }
                                                onChange={(e) => {
                                                  handleInputValidationCatering(
                                                    e,
                                                    "est_ttl_spnd"
                                                  );
                                                }}
                                                className={styles.field_Number}
                                              />
                                              {Settings.CateringDetails.usd}
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={styles.Field_Name}
                                              title=""
                                              width="270"
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .changeFromPrev
                                              }
                                            </td>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <input
                                                tabIndex={2}
                                                type="text"
                                                name={
                                                  contextType.state.catering
                                                    .est_ttl_spnd_pct_lstyr
                                                }
                                                id={
                                                  contextType.state.catering
                                                    .est_ttl_spnd_pct_lstyr
                                                }
                                                value={
                                                  contextType.state.catering
                                                    .est_ttl_spnd_pct_lstyr
                                                }
                                                size={10}
                                                maxLength={3}
                                                onKeyPress={
                                                  Utils.NumberOnly_onkeypress
                                                }
                                                onChange={(e) => {
                                                  handlePercentageInputValidation(
                                                    e,
                                                    "est_ttl_spnd_pct_lstyr"
                                                  );
                                                }}
                                                className={styles.field_Number}
                                              />
                                              {Settings.CateringDetails.percent}
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={styles.Field_Name}
                                              title={
                                                Settings.CateringDetails
                                                  .leadingUSMarketsTitle
                                              }
                                              width="270"
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .leadingUSMarkets
                                              }
                                            </td>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <input
                                                tabIndex={3}
                                                type="text"
                                                name={
                                                  contextType.state.catering
                                                    .lead_us_mkts
                                                }
                                                id={
                                                  contextType.state.catering
                                                    .lead_us_mkts
                                                }
                                                value={
                                                  contextType.state.catering
                                                    .lead_us_mkts
                                                }
                                                onChange={(e) => {
                                                  handleInputValidationCatering(
                                                    e,
                                                    "lead_us_mkts"
                                                  );
                                                }}
                                                size={40}
                                                maxLength={40}
                                              />
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={styles.Field_Name}
                                              title={
                                                Settings.CateringDetails
                                                  .estNonUSSpendTitle
                                              }
                                              width="270"
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .estNonUSSpend
                                              }
                                            </td>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <input
                                                tabIndex={4}
                                                type="text"
                                                name={
                                                  contextType.state.catering
                                                    .est_non_us_bus
                                                }
                                                id={
                                                  contextType.state.catering
                                                    .est_non_us_bus
                                                }
                                                value={
                                                  contextType.state.catering
                                                    .est_non_us_bus
                                                }
                                                size={20}
                                                maxLength={12}
                                                onKeyPress={
                                                  Utils.NumberOnly_onkeypress
                                                }
                                                onChange={(e) => {
                                                  handleInputValidationCatering(
                                                    e,
                                                    "est_non_us_bus"
                                                  );
                                                }}
                                                className={styles.field_Number}
                                              />
                                              {Settings.CateringDetails.usd}
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={styles.Field_Name}
                                              title=""
                                              width="270"
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .changeFromNonUSPrev
                                              }
                                            </td>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <input
                                                tabIndex={5}
                                                type="text"
                                                name={
                                                  contextType.state.catering
                                                    .non_us_bus_chng_lstyr
                                                }
                                                id={
                                                  contextType.state.catering
                                                    .non_us_bus_chng_lstyr
                                                }
                                                value={
                                                  contextType.state.catering
                                                    .non_us_bus_chng_lstyr
                                                }
                                                size={10}
                                                maxLength={3}
                                                onKeyPress={
                                                  Utils.NumberOnly_onkeypress
                                                }
                                                onChange={(e) => {
                                                  handlePercentageInputValidation(
                                                    e,
                                                    "non_us_bus_chng_lstyr"
                                                  );
                                                }}
                                                className={styles.field_Number}
                                              />
                                              {Settings.CateringDetails.percent}
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={styles.Field_Name}
                                              title={
                                                Settings.CateringDetails
                                                  .leadingNonUSMarketsTitle
                                              }
                                              width="270"
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .leadingNonUSMarkets
                                              }
                                            </td>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <input
                                                tabIndex={6}
                                                type="text"
                                                name={
                                                  contextType.state.catering
                                                    .lead_non_us_mkts
                                                }
                                                id={
                                                  contextType.state.catering
                                                    .lead_non_us_mkts
                                                }
                                                value={
                                                  contextType.state.catering
                                                    .lead_non_us_mkts
                                                }
                                                onChange={(e) => {
                                                  handleInputValidationCatering(
                                                    e,
                                                    "lead_non_us_mkts"
                                                  );
                                                }}
                                                size={40}
                                                maxLength={40}
                                              />
                                            </td>
                                          </tr>
                                          <tr>
                                            <td width="264">&nbsp;</td>
                                          </tr>
                                          <tr>
                                            <td width="264" height="1">
                                              &nbsp;
                                            </td>
                                          </tr>
                                        </table>
                                      </p>
                                    </td>

                                    <td
                                      colSpan={2}
                                      className={styles.sectionHeader}
                                    ></td>
                                    <td width="440" vertical-align="top">
                                      <table className="menuWdth100-Height">
                                        <tr>
                                          <td
                                            colSpan={2}
                                            className={styles.instructionHeader}
                                          >
                                            {
                                              Settings.CateringDetails
                                                .marriottGrpHistory
                                            }
                                          </td>
                                        </tr>
                                        <tr>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            height="18"
                                          >
                                            &nbsp;
                                          </td>
                                        </tr>
                                        <tr>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            title={
                                              Settings.CateringDetails
                                                .marriottGrpCateringTitle
                                            }
                                            width="236"
                                          >
                                            {
                                              Settings.CateringDetails
                                                .marriottGrpCatering
                                            }
                                          </td>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            width="202"
                                          >
                                            <input
                                              tabIndex={14}
                                              type="text"
                                              name={
                                                contextType.state.catering.rev
                                              }
                                              id={
                                                contextType.state.catering.rev
                                              }
                                              value={
                                                contextType.state.catering.rev
                                              }
                                              size={20}
                                              maxLength={12}
                                              onKeyPress={
                                                Utils.NumberOnly_onkeypress
                                              }
                                              onChange={(e) => {
                                                handleInputValidationCatering(
                                                  e,
                                                  "rev"
                                                );
                                              }}
                                              className={styles.field_Number}
                                            />
                                            {Settings.CateringDetails.usd}
                                          </td>
                                        </tr>
                                        <tr>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            title=""
                                            width="236"
                                          >
                                            {
                                              Settings.CateringDetails
                                                .changeFromGroupPrev
                                            }
                                          </td>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            width="202"
                                          >
                                            <input
                                              tabIndex={15}
                                              type="text"
                                              name={
                                                contextType.state.catering
                                                  .rev_chng_lstyr
                                              }
                                              id={
                                                contextType.state.catering
                                                  .rev_chng_lstyr
                                              }
                                              value={
                                                contextType.state.catering
                                                  .rev_chng_lstyr
                                              }
                                              size={10}
                                              maxLength={3}
                                              onKeyPress={
                                                Utils.NumberOnly_onkeypress
                                              }
                                              onChange={(e) => {
                                                handlePercentageInputValidation(
                                                  e,
                                                  "rev_chng_lstyr"
                                                );
                                              }}
                                              className={styles.field_Number}
                                            />
                                            {Settings.CateringDetails.percent}
                                          </td>
                                        </tr>
                                        <tr>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            title={
                                              Settings.CateringDetails
                                                .percTotalRevTitle
                                            }
                                            width="236"
                                          >
                                            {
                                              Settings.CateringDetails
                                                .percTotalRev
                                            }
                                          </td>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            width="202"
                                          >
                                            <input
                                              tabIndex={16}
                                              type="text"
                                              name={
                                                contextType.state.catering
                                                  .ttl_rev_pct
                                              }
                                              id={
                                                contextType.state.catering
                                                  .ttl_rev_pct
                                              }
                                              value={
                                                contextType.state.catering
                                                  .ttl_rev_pct
                                              }
                                              size={5}
                                              maxLength={3}
                                              onKeyPress={
                                                Utils.NumberOnly_onkeypress
                                              }
                                              onBlur={(e) => {
                                                handleTabInputValidation(
                                                  e,
                                                  "ttl_rev_pct"
                                                );
                                              }}
                                              onChange={(e) => {
                                                handlePercentageInputValidation(
                                                  e,
                                                  "ttl_rev_pct"
                                                );
                                              }}
                                              className={styles.field_Number}
                                            />
                                            {Settings.CateringDetails.percent}
                                          </td>
                                        </tr>
                                        <tr>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            title={
                                              Settings.CateringDetails
                                                .marriottLocalCateringTitle
                                            }
                                            width="236"
                                          >
                                            {
                                              Settings.CateringDetails
                                                .marriottLocalCatering
                                            }
                                          </td>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            width="202"
                                          >
                                            <input
                                              tabIndex={17}
                                              type="text"
                                              name={
                                                contextType.state.catering
                                                  .mar_lcl_rev
                                              }
                                              id={
                                                contextType.state.catering
                                                  .mar_lcl_rev
                                              }
                                              value={
                                                contextType.state.catering
                                                  .mar_lcl_rev
                                              }
                                              size={20}
                                              maxLength={12}
                                              onKeyPress={
                                                Utils.NumberOnly_onkeypress
                                              }
                                              onChange={(e) => {
                                                handleInputValidationCatering(
                                                  e,
                                                  "mar_lcl_rev"
                                                );
                                              }}
                                              className={styles.field_Number}
                                            />
                                            {Settings.CateringDetails.usd}
                                          </td>
                                        </tr>
                                        <tr>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            title=""
                                            width="236"
                                          >
                                            {
                                              Settings.CateringDetails
                                                .changeFromLocalPrev
                                            }
                                          </td>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            width="202"
                                          >
                                            <input
                                              tabIndex={18}
                                              type="text"
                                              name={
                                                contextType.state.catering
                                                  .mar_lcl_rev_chng_lstyr
                                              }
                                              id={
                                                contextType.state.catering
                                                  .mar_lcl_rev_chng_lstyr
                                              }
                                              value={
                                                contextType.state.catering
                                                  .mar_lcl_rev_chng_lstyr
                                              }
                                              size={10}
                                              maxLength={3}
                                              onKeyPress={
                                                Utils.NumberOnly_onkeypress
                                              }
                                              onChange={(e) => {
                                                handlePercentageInputValidation(
                                                  e,
                                                  "mar_lcl_rev_chng_lstyr"
                                                );
                                              }}
                                              className={styles.field_Number}
                                            />
                                            {Settings.CateringDetails.percent}
                                          </td>
                                        </tr>
                                        <tr>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            title={
                                              Settings.CateringDetails
                                                .totalSpendProjectionsTitle
                                            }
                                            width="236"
                                          >
                                            {
                                              Settings.CateringDetails
                                                .totalSpendProjections
                                            }
                                          </td>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            width="202"
                                          >
                                            <input
                                              tabIndex={19}
                                              type="text"
                                              name={
                                                contextType.state.catering
                                                  .ttl_projections
                                              }
                                              id={
                                                contextType.state.catering
                                                  .ttl_projections
                                              }
                                              value={
                                                contextType.state.catering
                                                  .ttl_projections
                                              }
                                              size={20}
                                              maxLength={12}
                                              onKeyPress={
                                                Utils.NumberOnly_onkeypress
                                              }
                                              onChange={(e) => {
                                                handleInputValidationCatering(
                                                  e,
                                                  "ttl_projections"
                                                );
                                              }}
                                              className={styles.field_Number}
                                            />
                                            {Settings.CateringDetails.usd}
                                          </td>
                                        </tr>
                                        <tr>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            title={
                                              Settings.CateringDetails
                                                .percenTotalRevTitle
                                            }
                                            width="236"
                                          >
                                            {
                                              Settings.CateringDetails
                                                .percenTotalRev
                                            }
                                          </td>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            width="202"
                                          >
                                            <input
                                              tabIndex={20}
                                              type="text"
                                              name={
                                                contextType.state.catering
                                                  .ttl_proj_rev_pct
                                              }
                                              id={
                                                contextType.state.catering
                                                  .ttl_proj_rev_pct
                                              }
                                              value={
                                                contextType.state.catering
                                                  .ttl_proj_rev_pct
                                              }
                                              size={5}
                                              maxLength={3}
                                              onKeyPress={
                                                Utils.NumberOnly_onkeypress
                                              }
                                              onBlur={(e) => {
                                                handleTabInputValidation(
                                                  e,
                                                  "ttl_proj_rev_pct"
                                                );
                                              }}
                                              onChange={(e) => {
                                                handlePercentageInputValidation(
                                                  e,
                                                  "ttl_proj_rev_pct"
                                                );
                                              }}
                                              className={styles.field_Number}
                                            />
                                            {Settings.CateringDetails.percent}
                                          </td>
                                        </tr>
                                        <tr>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            title={
                                              Settings.CateringDetails
                                                .bookingAgentTitle
                                            }
                                            width="236"
                                          >
                                            {
                                              Settings.CateringDetails
                                                .bookingAgent
                                            }
                                          </td>
                                          <td
                                            className={
                                              styles.Field_Name_Sections
                                            }
                                            width="202"
                                          >
                                            <input
                                              tabIndex={21}
                                              type="text"
                                              name={
                                                contextType.state
                                                  .revStreamDescription
                                                  .bkg_agent
                                              }
                                              id={
                                                contextType.state
                                                  .revStreamDescription
                                                  .bkg_agent
                                              }
                                              value={
                                                contextType.state
                                                  .revStreamDescription
                                                  .bkg_agent
                                              }
                                              onChange={(e) => {
                                                handleInputValidationRevenue(
                                                  e,
                                                  "bkg_agent"
                                                );
                                              }}
                                              size={20}
                                              maxLength={50}
                                            />
                                          </td>
                                        </tr>
                                      </table>
                                    </td>
                                  </tr>

                                  <table className={styles.sectionWidth}>
                                    <tr>
                                      <td
                                        colSpan={2}
                                        className={styles.instructionHeader}
                                        height="10"
                                      >
                                        {Settings.CateringDetails.businessInfo}
                                      </td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                      <td
                                        className={styles.Field_Name}
                                        title={
                                          Settings.CateringDetails
                                            .leadingCateringMarketTitle
                                        }
                                        width="270"
                                      >
                                        {
                                          Settings.CateringDetails
                                            .leadingCateringMarket
                                        }
                                      </td>
                                      <td
                                        className={styles.Field_Name_Sections}
                                      >
                                        <input
                                          type="text"
                                          tabIndex={7}
                                          name={
                                            contextType.state.catering.lead_mkts
                                          }
                                          id={
                                            contextType.state.catering.lead_mkts
                                          }
                                          value={
                                            contextType.state.catering.lead_mkts
                                          }
                                          onChange={(e) => {
                                            handleInputValidationCatering(
                                              e,
                                              "lead_mkts"
                                            );
                                          }}
                                          size={40}
                                          maxLength={40}
                                        />
                                      </td>
                                    </tr>
                                    <tr>
                                      <td
                                        className={styles.Field_Name}
                                        title=""
                                        width="270"
                                        style={{ paddingRight: "0px" }}
                                      >
                                        {
                                          Settings.CateringDetails
                                            .accountPlanOrLargeProd
                                        }
                                      </td>
                                      <td
                                        className={styles.Field_Name_Sections}
                                      >
                                        <input
                                          tabIndex={8}
                                          type="text"
                                          name={
                                            contextType.state.catering
                                              .act_pln_event
                                          }
                                          id={
                                            contextType.state.catering
                                              .act_pln_event
                                          }
                                          value={
                                            contextType.state.catering
                                              .act_pln_event
                                          }
                                          onChange={(e) => {
                                            handleInputValidationCatering(
                                              e,
                                              "act_pln_event"
                                            );
                                          }}
                                          size={40}
                                          maxLength={40}
                                        />
                                      </td>
                                    </tr>
                                    <tr>
                                      <td
                                        className={styles.Field_Name}
                                        title={
                                          Settings.CateringDetails
                                            .avgMeetingSizeTitle
                                        }
                                        width="270"
                                      >
                                        {
                                          Settings.CateringDetails
                                            .avgMeetingSize
                                        }
                                      </td>
                                      <td
                                        className={styles.Field_Name_Sections}
                                      >
                                        <input
                                          tabIndex={9}
                                          type="text"
                                          name={
                                            contextType.state
                                              .revStreamDescription.mtg_size
                                          }
                                          id={
                                            contextType.state
                                              .revStreamDescription.mtg_size
                                          }
                                          value={
                                            contextType.state
                                              .revStreamDescription.mtg_size
                                          }
                                          size={20}
                                          maxLength={12}
                                          onKeyPress={
                                            Utils.NumberOnly_onkeypress
                                          }
                                          onChange={(e) => {
                                            handleInputValidationRevenue(
                                              e,
                                              "mtg_size"
                                            );
                                          }}
                                          className={styles.field_Number}
                                        />
                                      </td>
                                    </tr>
                                    <tr>
                                      <td
                                        className={styles.Field_Name}
                                        title={
                                          Settings.CateringDetails
                                            .avgMeetingFreqTitle
                                        }
                                        width="270"
                                      >
                                        {
                                          Settings.CateringDetails
                                            .avgMeetingFreq
                                        }
                                      </td>
                                      <td
                                        className={styles.Field_Name_Sections}
                                      >
                                        <input
                                          tabIndex={10}
                                          type="text"
                                          name={
                                            contextType.state
                                              .revStreamDescription.mtg_freq
                                          }
                                          id={
                                            contextType.state
                                              .revStreamDescription.mtg_freq
                                          }
                                          value={
                                            contextType.state
                                              .revStreamDescription.mtg_freq
                                          }
                                          onChange={(e) => {
                                            handleInputValidationRevenue(
                                              e,
                                              "mtg_freq"
                                            );
                                          }}
                                          size={20}
                                          maxLength={100}
                                        />
                                      </td>
                                    </tr>
                                    <tr>
                                      <td className={styles.Field_Name}>
                                        {
                                          Settings.CateringDetails
                                            .holidayParties
                                        }
                                      </td>
                                      <td>
                                        <select
                                          tabIndex={11}
                                          name={
                                            contextType.state.catering
                                              .holiday_parties
                                          }
                                          id={
                                            contextType.state.catering
                                              .holiday_parties
                                          }
                                          value={
                                            contextType.state.catering
                                              .holiday_parties
                                          }
                                          onChange={(e) => {
                                            handleDropdownSelection(
                                              e,
                                              "holiday_parties"
                                            );
                                          }}
                                          size={1}
                                        >
                                          <option value=""></option>
                                          <option value="Y">
                                            {
                                              Settings.CateringDetails
                                                .holidayPartiesYes
                                            }
                                          </option>
                                          <option value="N">
                                            {
                                              Settings.CateringDetails
                                                .holidayPartiesNo
                                            }
                                          </option>
                                        </select>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td
                                        className={styles.Field_Name}
                                        title={
                                          Settings.CateringDetails
                                            .describeMarketsOrDetailsTitle
                                        }
                                        width="270"
                                      >
                                        {
                                          Settings.CateringDetails
                                            .describeMarketsOrDetails
                                        }
                                      </td>
                                      <td
                                        className={styles.Field_Name_Sections}
                                      >
                                        <input
                                          tabIndex={12}
                                          type="text"
                                          name={
                                            contextType.state.catering
                                              .holiday_party_details
                                          }
                                          id={
                                            contextType.state.catering
                                              .holiday_party_details
                                          }
                                          value={
                                            contextType.state.catering
                                              .holiday_party_details
                                          }
                                          size={40}
                                          onKeyPress={(e) =>
                                            Utils.checklen_onkeypress(e, 1024)
                                          }
                                          onChange={(e) => {
                                            handleCateringTextAreaInputValidation(
                                              e,
                                              "holiday_party_details"
                                            );
                                          }}
                                        />
                                      </td>
                                    </tr>
                                    <tr>
                                      <td className={styles.Field_Name}>
                                        {
                                          Settings.CateringDetails
                                            .telepresenseCap
                                        }
                                      </td>
                                      <td>
                                        <select
                                          tabIndex={13}
                                          name={
                                            contextType.state.catering
                                              .telepresence_caps
                                          }
                                          id={
                                            contextType.state.catering
                                              .telepresence_caps
                                          }
                                          value={
                                            contextType.state.catering
                                              .telepresence_caps
                                          }
                                          onChange={(e) => {
                                            handleDropdownSelection(
                                              e,
                                              "telepresence_caps"
                                            );
                                          }}
                                          size={1}
                                        >
                                          <option value=""></option>
                                          <option value="Y">
                                            {
                                              Settings.CateringDetails
                                                .telepresenseCapYes
                                            }
                                          </option>
                                          <option value="N">
                                            {
                                              Settings.CateringDetails
                                                .telepresenseCapNo
                                            }
                                          </option>
                                        </select>
                                      </td>
                                    </tr>
                                  </table>

                                  <table className="menuWdth100-Height">
                                    <tr>
                                      <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                      <td
                                        className={styles.instructionHeader}
                                        height="10"
                                      >
                                        {
                                          Settings.CateringDetails
                                            .businessLocalCatering
                                        }
                                      </td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                      <td>
                                        <table className="menuWdth100-Height">
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                              text-align="left"
                                              title={
                                                Settings.CateringDetails
                                                  .orgStructureTitle
                                              }
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .orgStructure
                                              }
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <textarea
                                                tabIndex={22}
                                                name={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .org_buying_struct
                                                }
                                                id={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .org_buying_struct
                                                }
                                                value={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .org_buying_struct
                                                }
                                                rows={4}
                                                cols={188}
                                                onKeyPress={(e) =>
                                                  Utils.checklen_onkeypress(
                                                    e,
                                                    1024
                                                  )
                                                }
                                                onChange={(e) => {
                                                  handleTextAreaInputValidation(
                                                    e,
                                                    "org_buying_struct"
                                                  );
                                                }}
                                              ></textarea>
                                            </td>
                                          </tr>
                                        </table>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                      <td>
                                        <table className="menuWdth100-Height">
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                              text-align="left"
                                              title={
                                                Settings.CateringDetails
                                                  .avgMeetingsTitle
                                              }
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .avgMeetings
                                              }
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <textarea
                                                tabIndex={23}
                                                name={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .mtg_types
                                                }
                                                id={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .mtg_types
                                                }
                                                value={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .mtg_types
                                                }
                                                rows={4}
                                                cols={188}
                                                onKeyPress={(e) =>
                                                  Utils.checklen_onkeypress(
                                                    e,
                                                    300
                                                  )
                                                }
                                                onChange={(e) => {
                                                  handleTextAreaInputValidation(
                                                    e,
                                                    "mtg_types"
                                                  );
                                                }}
                                              ></textarea>
                                            </td>
                                          </tr>
                                        </table>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                      <td>
                                        <table className="menuWdth100-Height">
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                              text-align="left"
                                              title={
                                                Settings.CateringDetails
                                                  .acctPoliciesProcOrMandatesTitle
                                              }
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .acctPoliciesProcOrMandates
                                              }
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <textarea
                                                tabIndex={24}
                                                name={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .policies
                                                }
                                                id={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .policies
                                                }
                                                value={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .policies
                                                }
                                                rows={4}
                                                cols={188}
                                                onKeyPress={(e) =>
                                                  Utils.checklen_onkeypress(
                                                    e,
                                                    1024
                                                  )
                                                }
                                                onChange={(e) => {
                                                  handleTextAreaInputValidation(
                                                    e,
                                                    "policies"
                                                  );
                                                }}
                                              ></textarea>
                                            </td>
                                          </tr>
                                        </table>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                      <td>
                                        <table className="menuWdth100-Height">
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                              text-align="left"
                                              title={
                                                Settings.CateringDetails
                                                  .preferredMarriottBrandsTitle
                                              }
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .preferredMarriottBrands
                                              }
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <textarea
                                                tabIndex={25}
                                                name={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .pref_brand
                                                }
                                                id={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .pref_brand
                                                }
                                                value={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .pref_brand
                                                }
                                                rows={4}
                                                cols={188}
                                                onKeyPress={(e) =>
                                                  Utils.checklen_onkeypress(
                                                    e,
                                                    1024
                                                  )
                                                }
                                                onChange={(e) => {
                                                  handleTextAreaInputValidation(
                                                    e,
                                                    "pref_brand"
                                                  );
                                                }}
                                              ></textarea>
                                            </td>
                                          </tr>
                                        </table>
                                      </td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                      <td>
                                        <table className="menuWdth100-Height">
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                              text-align="left"
                                              title={
                                                Settings.CateringDetails
                                                  .topCompetitorsTitle
                                              }
                                            >
                                              {
                                                Settings.CateringDetails
                                                  .topCompetitors
                                              }
                                            </td>
                                          </tr>
                                          <tr>
                                            <td
                                              className={
                                                styles.Field_Name_Sections
                                              }
                                            >
                                              <textarea
                                                tabIndex={25}
                                                name={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .competitors_bybrand
                                                }
                                                id={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .competitors_bybrand
                                                }
                                                value={
                                                  contextType.state
                                                    .revStreamDescription
                                                    .competitors_bybrand
                                                }
                                                rows={4}
                                                cols={188}
                                                onKeyPress={(e) =>
                                                  Utils.checklen_onkeypress(
                                                    e,
                                                    1024
                                                  )
                                                }
                                                onChange={(e) => {
                                                  handleTextAreaInputValidation(
                                                    e,
                                                    "competitors_bybrand"
                                                  );
                                                }}
                                              ></textarea>
                                            </td>
                                          </tr>
                                        </table>
                                      </td>
                                    </tr>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      )}
                    </React.Fragment>
                  );
                }}
              </CateringContext.Consumer>
            </CateringContextProvider>
            <style>{`
              .container{
                min-width:1100px;
              }
        `}</style>
          </Layout>
        );
      }}
    </SalesAdministartionContext.Consumer>
  );
};

export default Catering;
