const Settings = {
  api: {
    getEditLoaction: "/editLocation/getEditLocation",
    updateLocation: "/editLocation/updateLocation?nextUrl=/acctlocations/view",
    deleteLocation: "/editLocation/deleteLocation?nextUrl=/acctlocations/view",
    getEditInitiative: "/editInitiative/getEditInitiative",
    updateEditInitiative: "/editInitiative/getUpdateLocInitiative",
    deleteEditInitiative: "/editInitiative/getDeleteLocInitiative",
  },
  parentRoute: "/editaccountplansapp",
  fieldLabels: {
    initiativeName: "Initiative Name: ",
    responsible: "Responsible: ",
    initiativeYear: "Initiative Year: ",
    revenueStream: "Revenue Stream: ",
    initiativeAction: "Initiative/Action: ",
    objective: "Objective: ",
    executionPlan: "Execution Plan: ",
    resultsLearnings: "Results/Learnings: ",
    additionalComments: "Additional Comments: ",
    locationName: "Location Name:",
    organization: "Organization:",
    rmNt: "Buying Location Total Area Rm Nt Production (MRDW):",
    totalRevenue: "Buying Location Total Area Revenue Production (MRDW):",
    address: "Address",
    streetNumber: "Street Number & Name:",
    city: "City:",
    state: "State:",
    zipCode: "Zip Code:",
    country: "Country:",
    countryOrRegion: "Country/Region:",
    officeDescription: "Office Description/Contacts/Additional Information:",
    hotels: "Competitor Hotels:",
    marriottContact: "Marriott Contact ",
    name: "Name:",
    title: "Title:",
    phone: "Phone:",
    email: "Email:",
    beginDate: "Begin Date:",
    endDate: "End Date:",
    taskDescription: "Task Description:",
    locationAddress: "Brand Segment Preference for Location",
  },
  headingNames: {
    requiredFields: "* Required Fields are in red",
    modalHeading: "Alert Message",
    initiative: "Initiatives and Tasks:",
  },
  commontext: {
    loadingMessage: "Please wait loading...",
    deleteWarning:
      "Are you sure you want to delete this data?\n\nPlease click OK to continue, CANCEL to stop",
  },
  validationMessages: {
    locationName: "Location name is a required field.",
    orgName: "Please select an organization",
    rmnts:
      "Location Total Potential Room Nights is a required field and should be greater than zero.",
    marriottContactone: "Marriott Contact 1 - Name is a required field.",
    charExceedingAlert: "You are allowed to enter up to 1024 characters.",
    officeDescription:
      "'Office Description/Contacts/Additional Information' text cannot exceed 1024 characters.",
    hotels: "'Competitor Hotels' text cannot exceed 1024 characters.",
    action: "'Initiative/Action' text cannot exceed 1024 characters.",
    objective: "'Objective' text cannot exceed 1024 characters.",
    execPlan: "'Execution Plan' text cannot exceed 1024 characters.",
    results: "'Results/Learnings:' text cannot exceed 1024 characters.",
    comments: "'Additional Comments' text cannot exceed 1024 characters.",
    validEmail: "Please enter a valid email",
    initiativeName: "Inititative Name is a required fielid",
  },
  tooltip: {
    locationName: "What location are you in (the Marriott team member)",
    orgName: "Choose an organization for your location",
    initiative: "Which brands does the account prefer to utilize?",
    responsible:
      "Which Marriott contact is responsible/accountable for this specific initiative?",
    initiativeYear: "What is the date of the initiation of the initiative?",
    execplan:
      "List Individual Task names and dates, Team members responsible and task names here.",
    startDate: "What is the start date of the task?",
    responsibleTask: "Who owns the task?",
    endDate: "What is the expected end date of the task?",
    rmnts: "What is your location’s total potential Rm Nts for this account",
    totalRevenue:
      "What is your location’s total potential revenue for this account",
    streetNumber: "Street Number and Name",
    city: "City",
    state: "State",
    zipCode: "Zip code",
    country: "Country",
    locationAddress: "Location Address",
    marriottContact: "Marriott's Contact Information",
  },
  common: {
    numberRegex: /^[0-9\b]+$/,
    dateRegex: /^-?\d*\.?\d*$/,
    re_phone_number: /(^[0-9]+$|[-]$|[0-9]+$|^$)/,
  },
};
export default Settings;
