//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.product.batch;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.marriott.rfp.webservice.product.batch package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.marriott.rfp.webservice.product.batch
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccountBatchProductMasterProcess }
     * 
     */
    public AccountBatchProductMasterProcess createAccountBatchProductMasterProcess() {
        return new AccountBatchProductMasterProcess();
    }

    /**
     * Create an instance of {@link HotelProductProcessResponse }
     * 
     */
    public HotelProductProcessResponse createHotelProductProcessResponse() {
        return new HotelProductProcessResponse();
    }

    /**
     * Create an instance of {@link AccountBatchProductVerifyProcess }
     * 
     */
    public AccountBatchProductVerifyProcess createAccountBatchProductVerifyProcess() {
        return new AccountBatchProductVerifyProcess();
    }

    /**
     * Create an instance of {@link AccountBatchProductVerifyProcesssResponse }
     * 
     */
    public AccountBatchProductVerifyProcesssResponse createAccountBatchProductVerifyProcesssResponse() {
        return new AccountBatchProductVerifyProcesssResponse();
    }

    /**
     * Create an instance of {@link AccountBatchProductMasterProcessResponse }
     * 
     */
    public AccountBatchProductMasterProcessResponse createAccountBatchProductMasterProcessResponse() {
        return new AccountBatchProductMasterProcessResponse();
    }

    /**
     * Create an instance of {@link HotelProductProcess }
     * 
     */
    public HotelProductProcess createHotelProductProcess() {
        return new HotelProductProcess();
    }

}
