const Settings = {
  api: {
    getReports: "/pricingreportnofilterlist/getReportNoFilterViewLists.action",
    getData: "/pricingreportnofilterlist/getReportNoFilterViewLists.action",
    runReport: "/pricingreportnofilterlist/runReport.action",
    getCognosUrl: "/reports/getAppEnvDetails.action",
  },
  errorMessage: "There has been a technical Error. Please try again later.",
  errorUrl: "/errors/errors.action",
  homeUrl: "/pricingreportnofilter/view.action",
  requestSpecialReports: "Pricing Reports : Request Special Reports",
  yes: {
    value: "Y",
  },
  pgoosError: "ePgoosErrorException",
  no: {
    value: "N",
  },
  yesVal: "Yes",
  noVal: "No",
  l: {
    value: "L",
  },
  banner: "banner",
  labels: {
    emailreport: "Email me when report is ready",
    Report: "Report:",
    Year: "Year:",
    accountType: "Account Type:",
    account: "Account:",
    subCategory: "Sub-Category",
    optional: "(Optional):",
    region: "Region:",
    eid: "EID:",
    hotel: "Marsha Code:",
    role: "Role:",
    quarter: "Quarter:",
    module: "Module:",
    globalTeamLead: "Global Team Leader:",
    dateRange: "Date From:",
    pgoosStatus: "PGOOS Status:",
  },
  emailMe: "filterValues.emailMe",
  ControlKeyValues: {
    cSelectKeyField: "report_name",
    cSelectValueField: "report_title",
  },
  period: {
    id: "period",
    label: "Period: ",
    keyField: "period",
    valField: "period",
  },
  accountType: {
    id: "accountType",
    label: "Account Segment: ",
    keyField: "accounttype",
    valField: "accounttypedescription",
  },
  account: {
    id: "accountrecid",
    keyField: "accountrecid",
    valField: "accountname",
  },
  proximityList: {
    id: "proximitySubCatCode",
    keyField: "siccode1",
    valField: "siccode1desc",
  },
  region: {
    id: "regionid",
    keyField: "areaid",
    valField: "areaname",
  },
  hotel: {
    id: "marshaCode",
    keyField: "marshacode",
    valField: "name",
  },
  role: {
    id: "role",
    keyField: "role",
    valField: "role",
  },
  quarter: {
    id: "quarter",
    keyField: "quartername",
    valField: "description",
  },
  module: {
    id: "sappModule",
    keyField: "moduleid",
    valField: "modulename",
  },
  globalLeader: {
    id: "globalLeaderEID",
    keyField: "eid",
    valField: "fullName",
  },
  accountRegistration: "AccountRegistration",

  alttext: {
    submitBtnAltText: "Submit",
  },

  recorddropdown: {
    id: "report_name",
    name: "report_name",
  },
  allnewregistrations: {
    id: "filterValues.allnewregistrations",
    name: "filterValues.allnewregistrations",
  },
  showchange: {
    id: "showchange",
  },
  changeDate: {
    id: "filterValues.changeDate",
    name: "filterValues.changeDate",
  },
  retrievebtn: {
    id: "retrievebtn",
  },
  table1: {
    id: "TABLE1",
  },
  retrieveSubCat: {
    id: "filterValues.retrieveSubCat",
    name: "filterValues.retrieveSubCat",
  },
  eid: {
    id: "filterValues.eid",
    name: "filterValues.eid",
  },
  dateRangeFilter: {
    fromDate: {
      id: "strFromDate",
      name: "filterValues.dateRangeFilter.strFromDate",
    },
    toDate: {
      id: "strToDate",
      name: "filterValues.dateRangeFilter.strToDate",
    },
  },
  pgoosStatus: {
    statusError: {
      id: "filterValues.pgoosStatus.statusError",
      name: "filterValues.pgoosStatus.statusError",
    },
    statusInProgress: {
      id: "filterValues.pgoosStatus.statusInProgress",
      name: "filterValues.pgoosStatus.statusInProgress",
    },
    statusPublished: {
      id: "filterValues.pgoosStatus.statusPublished",
      name: "filterValues.pgoosStatus.statusPublished",
    },
  },
  blankReport: {
    report_name: 0,
    report_title: "*",
    is_electronic: null,
    allow_accounttype: null,
    allow_account: null,
    allow_period: null,
    add_params: null,
    req_account: null,
    req_roles: null,
    allow_region: null,
    allow_proximitysubcat: null,
    schedule_time: null,
    priority: null,
    req_acct_or_region: null,
    req_daterange: null,
    fsale_all_hotels: null,
    allow_account_eligible: null,
    allow_quarter: null,
    acctplan_options: null,
    sale_all_account: null,
    allow_saleslist: null,
    allow_apadminview: null,
    allow_account_solicited: null,
    include_marriott_contact: null,
    allow_onehotel: null,
    allow_eid: null,
    allow_futureopenings: null,
    allow_dateformat: null,
    req_acct_region_brand: null,
    allow_schedule: null,
    allow_cbchotels: null,
    allow_pgoosStatus: null,
    amenity_count: null,
  },
  blankAccountSegment: {
    accounttype: 0,
    accounttypedescription: "*",
  },
  blankAccount: {
    accountrecid: 0,
    accountname: "*",
  },
  blankProximity: {
    siccode1: "",
    siccode1desc: "*",
  },
  blankRegion: {
    areaid: 0,
    areaname: "*",
  },
  blankHotel: {
    marshacode: 0,
    name: "*",
  },
  blankRole: {
    role: 0,
    roleValue: "*",
  },
  blankQuarter: {
    quartername: 0,
    description: "*",
  },
  blankAccPlanModule: {
    moduleid: 0,
    modulename: "*",
  },
  blankGlobalSales: {
    eid: 0,
    fullName: "*",
  },

  eEdieProfileUsage: "eEdieProfileUsage",
  initialStateData: {
    isDataLoaded: false,
    reportId: null,
    requestSpecialReportsData: {
      filterValues: {
        accountrecid: null,
        accountType: null,
        sappModule: null,
        eid: null,
        globalLeaderEID: null,
        marshaCode: null,
        period: null,
        proximitySubCatCode: null,
        quarter: null,
        report: null,
        retrieveSubCat: null,
        role: null,
        regionid: null,
        allnewregistrations: null,
        changeDate: null,
        dateRangeFilter: {
          fromDate: null,
          toDate: null,
          strFromDate: null,
          strToDate: null,
        },
        exceldateformat: "mm/dd/yyyy",
        pgoosStatus: {
          statusError: null,
          statusInProgress: null,
          statusPublished: null,
        },
        emailMe: "",
      },
      noFilterOptions: {
        noFilterLists: {
          periodList: null,
          accountList: null,
          accountSegmentList: null,
          quarterList: null,
          reportlist: [
            {
              report_name: null,
              report_title: null,
              is_electronic: null,
              allow_accounttype: null,
              allow_account: null,
              allow_period: null,
              add_params: null,
              req_account: null,
              req_roles: null,
              allow_region: null,
              allow_proximitysubcat: null,
              schedule_time: null,
              priority: null,
              req_acct_or_region: null,
              req_daterange: null,
              fsale_all_hotels: null,
              allow_account_eligible: null,
              allow_quarter: null,
              acctplan_options: null,
              sale_all_account: null,
              allow_saleslist: null,
              allow_apadminview: null,
              allow_account_solicited: null,
              include_marriott_contact: null,
              allow_onehotel: null,
              allow_eid: null,
              allow_futureopenings: null,
              allow_dateformat: null,
              req_acct_region_brand: null,
              allow_schedule: null,
              allow_cbchotels: null,
              allow_pgoosStatus: null,
              amenity_count: null,
            },
          ],
          sappmoduleList: null,
          proximityList: null,
          globalSalesContacts: null,
          regionList: null,
          roleList: null,
          hotelList: null,
          exceldateformat: null,
        },
        reportDetails: {
          report_name: null,
          report_title: null,
          is_electronic: null,
          allow_accounttype: null,
          allow_account: null,
          allow_period: null,
          add_params: null,
          req_account: null,
          req_roles: null,
          allow_region: null,
          allow_proximitysubcat: null,
          schedule_time: null,
          priority: null,
          req_acct_or_region: null,
          req_daterange: null,
          fsale_all_hotels: null,
          allow_account_eligible: null,
          allow_quarter: null,
          acctplan_options: null,
          sale_all_account: null,
          allow_saleslist: null,
          allow_apadminview: null,
          allow_account_solicited: null,
          include_marriott_contact: null,
          allow_onehotel: null,
          allow_eid: null,
          allow_futureopenings: null,
          allow_dateformat: null,
          req_acct_region_brand: null,
          allow_schedule: null,
          allow_cbchotels: null,
          allow_pgoosStatus: null,
          amenity_count: null,
        },
      },
    },

    selectedValues: {
      accountrecid: null,
      accountType: null,
      sappModule: null,
      eid: null,
      globalLeaderEID: null,
      marshaCode: null,
      period: null,
      proximitySubCatCode: null,
      quarter: null,
      report: null,
      retrieveSubCat: null,
      role: null,
      regionid: null,
      allnewregistrations: null,
      changeDate: null,
      dateRangeFilter: null,
      exceldateformat: "mm/dd/yyyy",
      pgoosStatus: null,
      emailMe: "",
    },
    dateChangeVal: "",
    isAllNew: true,
    isAllNewValue: "Y",
    statusError: true,
    statusErrorVal: "Y",
    statusInProgress: true,
    statusInProgressVal: "Y",
    statusPublished: false,
    statusPublishedVal: "",
    emailMe: false,
    retrieveSubCat: "N",
    isSubmitBtnClicked: false,
    hiddenUrl: null,
    reportUrl: null,
    defaultPeriod: null,
    isSbmtBtnDisable: false,
  },
};

export default Settings;
