//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarketSegmentCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="RoomPool" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CommissionableFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributesType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "marketSegmentCode",
    "roomPool",
    "commissionableFlag"
})
public class AttributesType {

    @XmlElement(name = "MarketSegmentCode")
    protected long marketSegmentCode;
    @XmlElement(name = "RoomPool", required = true)
    protected String roomPool;
    @XmlElement(name = "CommissionableFlag")
    protected boolean commissionableFlag;

    /**
     * Gets the value of the marketSegmentCode property.
     * 
     */
    public long getMarketSegmentCode() {
        return marketSegmentCode;
    }

    /**
     * Sets the value of the marketSegmentCode property.
     * 
     */
    public void setMarketSegmentCode(long value) {
        this.marketSegmentCode = value;
    }

    /**
     * Gets the value of the roomPool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomPool() {
        return roomPool;
    }

    /**
     * Sets the value of the roomPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomPool(String value) {
        this.roomPool = value;
    }

    /**
     * Gets the value of the commissionableFlag property.
     * 
     */
    public boolean isCommissionableFlag() {
        return commissionableFlag;
    }

    /**
     * Sets the value of the commissionableFlag property.
     * 
     */
    public void setCommissionableFlag(boolean value) {
        this.commissionableFlag = value;
    }

}
