//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvailabilityResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailabilityResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateRange" type="{http://com/marriott/rma/webservice/btrates}DateRangeType"/>
 *         &lt;element name="AvailabilityParent" type="{http://com/marriott/rma/webservice/btrates}ParentRateOfferResponseType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailabilityResponseType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "dateRange",
    "availabilityParent"
})
public class AvailabilityResponseType {

    @XmlElement(name = "DateRange", required = true)
    protected DateRangeType dateRange;
    @XmlElement(name = "AvailabilityParent", required = true)
    protected ParentRateOfferResponseType availabilityParent;

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeType }
     *     
     */
    public DateRangeType getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeType }
     *     
     */
    public void setDateRange(DateRangeType value) {
        this.dateRange = value;
    }

    /**
     * Gets the value of the availabilityParent property.
     * 
     * @return
     *     possible object is
     *     {@link ParentRateOfferResponseType }
     *     
     */
    public ParentRateOfferResponseType getAvailabilityParent() {
        return availabilityParent;
    }

    /**
     * Sets the value of the availabilityParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentRateOfferResponseType }
     *     
     */
    public void setAvailabilityParent(ParentRateOfferResponseType value) {
        this.availabilityParent = value;
    }

}
