//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for btPricingRuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="btPricingRuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="btRuleList" type="{http://com/marriott/rma/webservice/btrates}btRuleLosType" maxOccurs="4"/>
 *         &lt;element name="DateRange" type="{http://com/marriott/rma/webservice/btrates}DateRangeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "btPricingRuleType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "btRuleList",
    "dateRange"
})
public class BtPricingRuleType {

    @XmlElement(required = true)
    protected List<BtRuleLosType> btRuleList;
    @XmlElement(name = "DateRange", required = true)
    protected DateRangeType dateRange;

    /**
     * Gets the value of the btRuleList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the btRuleList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBtRuleList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BtRuleLosType }
     * 
     * 
     */
    public List<BtRuleLosType> getBtRuleList() {
        if (btRuleList == null) {
            btRuleList = new ArrayList<BtRuleLosType>();
        }
        return this.btRuleList;
    }

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeType }
     *     
     */
    public DateRangeType getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeType }
     *     
     */
    public void setDateRange(DateRangeType value) {
        this.dateRange = value;
    }

}
