//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "BTRateService", targetNamespace = "http://com/marriott/rma/webservice/btrates", wsdlLocation = "file:/C:/Users/gkris192/Git/MarRFP/rfp-business-publish-impl/src/main/resources/META-INF/wsdl/BTRateService.wsdl")
public class BTRateService
    extends Service
{

    private static final URL BTRATESERVICE_WSDL_LOCATION;
    private static final Logger logger = Logger.getLogger(com.marriott.rfp.webservice.hpp.btrates.BTRateService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.marriott.rfp.webservice.hpp.btrates.BTRateService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/gkris192/Git/MarRFP/rfp-business-publish-impl/src/main/resources/META-INF/wsdl/BTRateService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/gkris192/Git/MarRFP/rfp-business-publish-impl/src/main/resources/META-INF/wsdl/BTRateService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BTRATESERVICE_WSDL_LOCATION = url;
    }

    public BTRateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTRateService() {
        super(BTRATESERVICE_WSDL_LOCATION, new QName("http://com/marriott/rma/webservice/btrates", "BTRateService"));
    }

    /**
     * 
     * @return
     *     returns BTRateServicePortType
     */
    @WebEndpoint(name = "BTRateServicePort")
    public BTRateServicePortType getBTRateServicePort() {
        return super.getPort(new QName("http://com/marriott/rma/webservice/btrates", "BTRateServicePort"), BTRateServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTRateServicePortType
     */
    @WebEndpoint(name = "BTRateServicePort")
    public BTRateServicePortType getBTRateServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/marriott/rma/webservice/btrates", "BTRateServicePort"), BTRateServicePortType.class, features);
    }

}
