//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BTRateStatusReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BTRateStatusReqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="PropertyRateOfferId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="PropertyRateEntityId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BTRateStatusReqType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "transactionId",
    "propertyRateOfferId",
    "propertyRateEntityId"
})
public class BTRateStatusReqType {

    @XmlElement(name = "TransactionId")
    protected long transactionId;
    @XmlElement(name = "PropertyRateOfferId")
    protected long propertyRateOfferId;
    @XmlElement(name = "PropertyRateEntityId")
    protected long propertyRateEntityId;

    /**
     * Gets the value of the transactionId property.
     * 
     */
    public long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     */
    public void setTransactionId(long value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the propertyRateOfferId property.
     * 
     */
    public long getPropertyRateOfferId() {
        return propertyRateOfferId;
    }

    /**
     * Sets the value of the propertyRateOfferId property.
     * 
     */
    public void setPropertyRateOfferId(long value) {
        this.propertyRateOfferId = value;
    }

    /**
     * Gets the value of the propertyRateEntityId property.
     * 
     */
    public long getPropertyRateEntityId() {
        return propertyRateEntityId;
    }

    /**
     * Sets the value of the propertyRateEntityId property.
     * 
     */
    public void setPropertyRateEntityId(long value) {
        this.propertyRateEntityId = value;
    }

}
