//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProcessId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="PropertyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HoldPublish" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SendRateEntityList" type="{http://com/marriott/rma/webservice/btrates}RateEntityListType" minOccurs="0"/>
 *         &lt;element name="RelinquishRateEntityList" type="{http://com/marriott/rma/webservice/btrates}RelinquishRateEntityListType" minOccurs="0"/>
 *         &lt;element name="KillRateEntityList" type="{http://com/marriott/rma/webservice/btrates}KillRateEntityListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processId",
    "propertyCode",
    "holdPublish",
    "eid",
    "sendRateEntityList",
    "relinquishRateEntityList",
    "killRateEntityList"
})
@XmlRootElement(name = "BTRatesRequest")
public class BTRatesRequest {

    @XmlElement(name = "ProcessId")
    protected long processId;
    @XmlElement(name = "PropertyCode", required = true)
    protected String propertyCode;
    @XmlElement(name = "HoldPublish")
    protected Boolean holdPublish;
    @XmlElement(name = "EID", required = true)
    protected String eid;
    @XmlElement(name = "SendRateEntityList")
    protected RateEntityListType sendRateEntityList;
    @XmlElement(name = "RelinquishRateEntityList")
    protected RelinquishRateEntityListType relinquishRateEntityList;
    @XmlElement(name = "KillRateEntityList")
    protected KillRateEntityListType killRateEntityList;

    /**
     * Gets the value of the processId property.
     * 
     */
    public long getProcessId() {
        return processId;
    }

    /**
     * Sets the value of the processId property.
     * 
     */
    public void setProcessId(long value) {
        this.processId = value;
    }

    /**
     * Gets the value of the propertyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyCode() {
        return propertyCode;
    }

    /**
     * Sets the value of the propertyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyCode(String value) {
        this.propertyCode = value;
    }

    /**
     * Gets the value of the holdPublish property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHoldPublish() {
        return holdPublish;
    }

    /**
     * Sets the value of the holdPublish property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHoldPublish(Boolean value) {
        this.holdPublish = value;
    }

    /**
     * Gets the value of the eid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEID() {
        return eid;
    }

    /**
     * Sets the value of the eid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEID(String value) {
        this.eid = value;
    }

    /**
     * Gets the value of the sendRateEntityList property.
     * 
     * @return
     *     possible object is
     *     {@link RateEntityListType }
     *     
     */
    public RateEntityListType getSendRateEntityList() {
        return sendRateEntityList;
    }

    /**
     * Sets the value of the sendRateEntityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateEntityListType }
     *     
     */
    public void setSendRateEntityList(RateEntityListType value) {
        this.sendRateEntityList = value;
    }

    /**
     * Gets the value of the relinquishRateEntityList property.
     * 
     * @return
     *     possible object is
     *     {@link RelinquishRateEntityListType }
     *     
     */
    public RelinquishRateEntityListType getRelinquishRateEntityList() {
        return relinquishRateEntityList;
    }

    /**
     * Sets the value of the relinquishRateEntityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelinquishRateEntityListType }
     *     
     */
    public void setRelinquishRateEntityList(RelinquishRateEntityListType value) {
        this.relinquishRateEntityList = value;
    }

    /**
     * Gets the value of the killRateEntityList property.
     * 
     * @return
     *     possible object is
     *     {@link KillRateEntityListType }
     *     
     */
    public KillRateEntityListType getKillRateEntityList() {
        return killRateEntityList;
    }

    /**
     * Sets the value of the killRateEntityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link KillRateEntityListType }
     *     
     */
    public void setKillRateEntityList(KillRateEntityListType value) {
        this.killRateEntityList = value;
    }

}
