//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BTRateStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BTRateStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="RequestType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="BtRates"/>
 *               &lt;enumeration value="Relinquish"/>
 *               &lt;enumeration value="Kill"/>
 *               &lt;enumeration value="Status"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RateOfferId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="RateProgram" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PropertyRateEntityId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="RateOfferName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PropertyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://com/marriott/rma/webservice/btrates}StatusType"/>
 *         &lt;element name="Source" type="{http://com/marriott/rma/webservice/btrates}SourceType"/>
 *         &lt;element name="LastPublishDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PurgeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CapsAndRestictionsParent" type="{http://com/marriott/rma/webservice/btrates}ParentRateOfferResponseType" minOccurs="0"/>
 *         &lt;element name="PricingResponseList" type="{http://com/marriott/rma/webservice/btrates}PricingResponseListType" minOccurs="0"/>
 *         &lt;element name="AvailabilityResponseList" type="{http://com/marriott/rma/webservice/btrates}AvailabilityResponseList" minOccurs="0"/>
 *         &lt;element name="ErrorList" type="{http://com/marriott/rma/webservice/btrates}ErrorList" minOccurs="0"/>
 *         &lt;element name="WarningList" type="{http://com/marriott/rma/webservice/btrates}WarningList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BTRateStatusType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "transactionId",
    "requestType",
    "rateOfferId",
    "rateProgram",
    "propertyRateEntityId",
    "rateOfferName",
    "propertyCode",
    "status",
    "source",
    "lastPublishDate",
    "purgeDate",
    "capsAndRestictionsParent",
    "pricingResponseList",
    "availabilityResponseList",
    "errorList",
    "warningList"
})
public class BTRateStatusType {

    @XmlElement(name = "TransactionId")
    protected long transactionId;
    @XmlElement(name = "RequestType", required = true)
    protected String requestType;
    @XmlElement(name = "RateOfferId")
    protected long rateOfferId;
    @XmlElement(name = "RateProgram", required = true)
    protected String rateProgram;
    @XmlElement(name = "PropertyRateEntityId")
    protected Long propertyRateEntityId;
    @XmlElement(name = "RateOfferName")
    protected String rateOfferName;
    @XmlElement(name = "PropertyCode", required = true)
    protected String propertyCode;
    @XmlElement(name = "Status", required = true)
    protected StatusType status;
    @XmlElement(name = "Source", required = true)
    protected SourceType source;
    @XmlElement(name = "LastPublishDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastPublishDate;
    @XmlElement(name = "PurgeDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar purgeDate;
    @XmlElement(name = "CapsAndRestictionsParent")
    protected ParentRateOfferResponseType capsAndRestictionsParent;
    @XmlElement(name = "PricingResponseList")
    protected PricingResponseListType pricingResponseList;
    @XmlElement(name = "AvailabilityResponseList")
    protected AvailabilityResponseList availabilityResponseList;
    @XmlElement(name = "ErrorList")
    protected ErrorList errorList;
    @XmlElement(name = "WarningList")
    protected WarningList warningList;

    /**
     * Gets the value of the transactionId property.
     * 
     */
    public long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     */
    public void setTransactionId(long value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestType(String value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the rateOfferId property.
     * 
     */
    public long getRateOfferId() {
        return rateOfferId;
    }

    /**
     * Sets the value of the rateOfferId property.
     * 
     */
    public void setRateOfferId(long value) {
        this.rateOfferId = value;
    }

    /**
     * Gets the value of the rateProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateProgram() {
        return rateProgram;
    }

    /**
     * Sets the value of the rateProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateProgram(String value) {
        this.rateProgram = value;
    }

    /**
     * Gets the value of the propertyRateEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPropertyRateEntityId() {
        return propertyRateEntityId;
    }

    /**
     * Sets the value of the propertyRateEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPropertyRateEntityId(Long value) {
        this.propertyRateEntityId = value;
    }

    /**
     * Gets the value of the rateOfferName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateOfferName() {
        return rateOfferName;
    }

    /**
     * Sets the value of the rateOfferName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateOfferName(String value) {
        this.rateOfferName = value;
    }

    /**
     * Gets the value of the propertyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyCode() {
        return propertyCode;
    }

    /**
     * Sets the value of the propertyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyCode(String value) {
        this.propertyCode = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceType }
     *     
     */
    public SourceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceType }
     *     
     */
    public void setSource(SourceType value) {
        this.source = value;
    }

    /**
     * Gets the value of the lastPublishDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastPublishDate() {
        return lastPublishDate;
    }

    /**
     * Sets the value of the lastPublishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastPublishDate(XMLGregorianCalendar value) {
        this.lastPublishDate = value;
    }

    /**
     * Gets the value of the purgeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPurgeDate() {
        return purgeDate;
    }

    /**
     * Sets the value of the purgeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPurgeDate(XMLGregorianCalendar value) {
        this.purgeDate = value;
    }

    /**
     * Gets the value of the capsAndRestictionsParent property.
     * 
     * @return
     *     possible object is
     *     {@link ParentRateOfferResponseType }
     *     
     */
    public ParentRateOfferResponseType getCapsAndRestictionsParent() {
        return capsAndRestictionsParent;
    }

    /**
     * Sets the value of the capsAndRestictionsParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentRateOfferResponseType }
     *     
     */
    public void setCapsAndRestictionsParent(ParentRateOfferResponseType value) {
        this.capsAndRestictionsParent = value;
    }

    /**
     * Gets the value of the pricingResponseList property.
     * 
     * @return
     *     possible object is
     *     {@link PricingResponseListType }
     *     
     */
    public PricingResponseListType getPricingResponseList() {
        return pricingResponseList;
    }

    /**
     * Sets the value of the pricingResponseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingResponseListType }
     *     
     */
    public void setPricingResponseList(PricingResponseListType value) {
        this.pricingResponseList = value;
    }

    /**
     * Gets the value of the availabilityResponseList property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityResponseList }
     *     
     */
    public AvailabilityResponseList getAvailabilityResponseList() {
        return availabilityResponseList;
    }

    /**
     * Sets the value of the availabilityResponseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityResponseList }
     *     
     */
    public void setAvailabilityResponseList(AvailabilityResponseList value) {
        this.availabilityResponseList = value;
    }

    /**
     * Gets the value of the errorList property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorList }
     *     
     */
    public ErrorList getErrorList() {
        return errorList;
    }

    /**
     * Sets the value of the errorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorList }
     *     
     */
    public void setErrorList(ErrorList value) {
        this.errorList = value;
    }

    /**
     * Gets the value of the warningList property.
     * 
     * @return
     *     possible object is
     *     {@link WarningList }
     *     
     */
    public WarningList getWarningList() {
        return warningList;
    }

    /**
     * Sets the value of the warningList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningList }
     *     
     */
    public void setWarningList(WarningList value) {
        this.warningList = value;
    }

}
