//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for btRuleLosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="btRuleLosType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RuleInfo" type="{http://com/marriott/rma/webservice/btrates}RuleType"/>
 *         &lt;element name="PricingParent" type="{http://com/marriott/rma/webservice/btrates}PricingParentType" minOccurs="0"/>
 *         &lt;element name="CeilingRuleInfo" type="{http://com/marriott/rma/webservice/btrates}AdjustmentRuleType" minOccurs="0"/>
 *         &lt;element name="CeilingParent" type="{http://com/marriott/rma/webservice/btrates}PricingParentType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="TierNumber" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *             &lt;element name="StartNight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *             &lt;element name="EndNight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="CurrentTierNumber" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *             &lt;element name="MirrorLOSStructureFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *           &lt;/sequence>
 *           &lt;element name="OccupancyID" type="{http://com/marriott/rma/webservice/btrates}OccupancyType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "btRuleLosType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "ruleInfo",
    "pricingParent",
    "ceilingRuleInfo",
    "ceilingParent",
    "tierNumber",
    "startNight",
    "endNight",
    "currentTierNumber",
    "mirrorLOSStructureFlag",
    "occupancyID"
})
public class BtRuleLosType {

    @XmlElement(name = "RuleInfo", required = true)
    protected RuleType ruleInfo;
    @XmlElement(name = "PricingParent")
    protected PricingParentType pricingParent;
    @XmlElement(name = "CeilingRuleInfo")
    protected AdjustmentRuleType ceilingRuleInfo;
    @XmlElement(name = "CeilingParent")
    protected PricingParentType ceilingParent;
    @XmlElement(name = "TierNumber")
    protected BigDecimal tierNumber;
    @XmlElement(name = "StartNight")
    protected BigDecimal startNight;
    @XmlElement(name = "EndNight")
    protected BigDecimal endNight;
    @XmlElement(name = "CurrentTierNumber")
    protected BigDecimal currentTierNumber;
    @XmlElement(name = "MirrorLOSStructureFlag")
    protected Boolean mirrorLOSStructureFlag;
    @XmlElement(name = "OccupancyID")
    protected Long occupancyID;

    /**
     * Gets the value of the ruleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getRuleInfo() {
        return ruleInfo;
    }

    /**
     * Sets the value of the ruleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     */
    public void setRuleInfo(RuleType value) {
        this.ruleInfo = value;
    }

    /**
     * Gets the value of the pricingParent property.
     * 
     * @return
     *     possible object is
     *     {@link PricingParentType }
     *     
     */
    public PricingParentType getPricingParent() {
        return pricingParent;
    }

    /**
     * Sets the value of the pricingParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingParentType }
     *     
     */
    public void setPricingParent(PricingParentType value) {
        this.pricingParent = value;
    }

    /**
     * Gets the value of the ceilingRuleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustmentRuleType }
     *     
     */
    public AdjustmentRuleType getCeilingRuleInfo() {
        return ceilingRuleInfo;
    }

    /**
     * Sets the value of the ceilingRuleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustmentRuleType }
     *     
     */
    public void setCeilingRuleInfo(AdjustmentRuleType value) {
        this.ceilingRuleInfo = value;
    }

    /**
     * Gets the value of the ceilingParent property.
     * 
     * @return
     *     possible object is
     *     {@link PricingParentType }
     *     
     */
    public PricingParentType getCeilingParent() {
        return ceilingParent;
    }

    /**
     * Sets the value of the ceilingParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingParentType }
     *     
     */
    public void setCeilingParent(PricingParentType value) {
        this.ceilingParent = value;
    }

    /**
     * Gets the value of the tierNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTierNumber() {
        return tierNumber;
    }

    /**
     * Sets the value of the tierNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTierNumber(BigDecimal value) {
        this.tierNumber = value;
    }

    /**
     * Gets the value of the startNight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStartNight() {
        return startNight;
    }

    /**
     * Sets the value of the startNight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStartNight(BigDecimal value) {
        this.startNight = value;
    }

    /**
     * Gets the value of the endNight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndNight() {
        return endNight;
    }

    /**
     * Sets the value of the endNight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndNight(BigDecimal value) {
        this.endNight = value;
    }

    /**
     * Gets the value of the currentTierNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentTierNumber() {
        return currentTierNumber;
    }

    /**
     * Sets the value of the currentTierNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentTierNumber(BigDecimal value) {
        this.currentTierNumber = value;
    }

    /**
     * Gets the value of the mirrorLOSStructureFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMirrorLOSStructureFlag() {
        return mirrorLOSStructureFlag;
    }

    /**
     * Sets the value of the mirrorLOSStructureFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMirrorLOSStructureFlag(Boolean value) {
        this.mirrorLOSStructureFlag = value;
    }

    /**
     * Gets the value of the occupancyID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOccupancyID() {
        return occupancyID;
    }

    /**
     * Sets the value of the occupancyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOccupancyID(Long value) {
        this.occupancyID = value;
    }

}
