//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistanceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DistanceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="mi"/>
 *     &lt;enumeration value="km"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DistanceType", namespace = "http://com/marriott/rma/webservice/btrates")
@XmlEnum
public enum DistanceType {

    @XmlEnumValue("mi")
    MI("mi"),
    @XmlEnumValue("km")
    KM("km");
    private final String value;

    DistanceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DistanceType fromValue(String v) {
        for (DistanceType c: DistanceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
