//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.ws.WebFault;

@SuppressWarnings("serial")
@WebFault(name = "FaultMessage", targetNamespace = "http://com/marriott/rma/webservice/btrates")
public class FaultMessage_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultMessage faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FaultMessage_Exception(String message, FaultMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public FaultMessage_Exception(String message, FaultMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.marriott.rfp.webservice.hpp.btrates.FaultMessage
     */
    public FaultMessage getFaultInfo() {
        return faultInfo;
    }

}
