//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ICDActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ICDActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BTBlackout"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ICDActionType", namespace = "http://com/marriott/rma/webservice/btrates")
@XmlEnum
public enum ICDActionType {

    @XmlEnumValue("BTBlackout")
    BT_BLACKOUT("BTBlackout");
    private final String value;

    ICDActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ICDActionType fromValue(String v) {
        for (ICDActionType c: ICDActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
