//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KillRateEntityListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KillRateEntityListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KillRateEntity" type="{http://com/marriott/rma/webservice/btrates}KillRateEntityType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KillRateEntityListType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "killRateEntity"
})
public class KillRateEntityListType {

    @XmlElement(name = "KillRateEntity", required = true)
    protected List<KillRateEntityType> killRateEntity;

    /**
     * Gets the value of the killRateEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the killRateEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKillRateEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KillRateEntityType }
     * 
     * 
     */
    public List<KillRateEntityType> getKillRateEntity() {
        if (killRateEntity == null) {
            killRateEntity = new ArrayList<KillRateEntityType>();
        }
        return this.killRateEntity;
    }

}
