//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KnownRateEntityIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KnownRateEntityIdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MirrorRateOfferId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="MirrorRateEntityId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KnownRateEntityIdType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "mirrorRateOfferId",
    "mirrorRateEntityId"
})
public class KnownRateEntityIdType {

    @XmlElement(name = "MirrorRateOfferId")
    protected long mirrorRateOfferId;
    @XmlElement(name = "MirrorRateEntityId")
    protected long mirrorRateEntityId;

    /**
     * Gets the value of the mirrorRateOfferId property.
     * 
     */
    public long getMirrorRateOfferId() {
        return mirrorRateOfferId;
    }

    /**
     * Sets the value of the mirrorRateOfferId property.
     * 
     */
    public void setMirrorRateOfferId(long value) {
        this.mirrorRateOfferId = value;
    }

    /**
     * Gets the value of the mirrorRateEntityId property.
     * 
     */
    public long getMirrorRateEntityId() {
        return mirrorRateEntityId;
    }

    /**
     * Sets the value of the mirrorRateEntityId property.
     * 
     */
    public void setMirrorRateEntityId(long value) {
        this.mirrorRateEntityId = value;
    }

}
