//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.marriott.rfp.webservice.hpp.btrates package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.marriott.rfp.webservice.hpp.btrates
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PropertyPublishResponseType }
     * 
     */
    public PropertyPublishResponseType createPropertyPublishResponseType() {
        return new PropertyPublishResponseType();
    }

    /**
     * Create an instance of {@link DateRangeType }
     * 
     */
    public DateRangeType createDateRangeType() {
        return new DateRangeType();
    }

    /**
     * Create an instance of {@link AttributesType }
     * 
     */
    public AttributesType createAttributesType() {
        return new AttributesType();
    }

    /**
     * Create an instance of {@link WarningList }
     * 
     */
    public WarningList createWarningList() {
        return new WarningList();
    }

    /**
     * Create an instance of {@link BTRatesResponse }
     * 
     */
    public BTRatesResponse createBTRatesResponse() {
        return new BTRatesResponse();
    }

    /**
     * Create an instance of {@link BTPublishResponse }
     * 
     */
    public BTPublishResponse createBTPublishResponse() {
        return new BTPublishResponse();
    }

    /**
     * Create an instance of {@link AvailabilityResponseType }
     * 
     */
    public AvailabilityResponseType createAvailabilityResponseType() {
        return new AvailabilityResponseType();
    }

    /**
     * Create an instance of {@link KillRateEntityType }
     * 
     */
    public KillRateEntityType createKillRateEntityType() {
        return new KillRateEntityType();
    }

    /**
     * Create an instance of {@link FaultMessage }
     * 
     */
    public FaultMessage createFaultMessage() {
        return new FaultMessage();
    }

    /**
     * Create an instance of {@link BTRateStatusReqType }
     * 
     */
    public BTRateStatusReqType createBTRateStatusReqType() {
        return new BTRateStatusReqType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link WarningType }
     * 
     */
    public WarningType createWarningType() {
        return new WarningType();
    }

    /**
     * Create an instance of {@link PricingRuleListType }
     * 
     */
    public PricingRuleListType createPricingRuleListType() {
        return new PricingRuleListType();
    }

    /**
     * Create an instance of {@link RelinquishRateEntityType }
     * 
     */
    public RelinquishRateEntityType createRelinquishRateEntityType() {
        return new RelinquishRateEntityType();
    }

    /**
     * Create an instance of {@link MirroringType }
     * 
     */
    public MirroringType createMirroringType() {
        return new MirroringType();
    }

    /**
     * Create an instance of {@link PricingResponseType }
     * 
     */
    public PricingResponseType createPricingResponseType() {
        return new PricingResponseType();
    }

    /**
     * Create an instance of {@link BtRuleLosType }
     * 
     */
    public BtRuleLosType createBtRuleLosType() {
        return new BtRuleLosType();
    }

    /**
     * Create an instance of {@link BTRateStatusType }
     * 
     */
    public BTRateStatusType createBTRateStatusType() {
        return new BTRateStatusType();
    }

    /**
     * Create an instance of {@link ParentRateOfferResponseType }
     * 
     */
    public ParentRateOfferResponseType createParentRateOfferResponseType() {
        return new ParentRateOfferResponseType();
    }

    /**
     * Create an instance of {@link MirrorAvailabilityType }
     * 
     */
    public MirrorAvailabilityType createMirrorAvailabilityType() {
        return new MirrorAvailabilityType();
    }

    /**
     * Create an instance of {@link KillRateEntityListType }
     * 
     */
    public KillRateEntityListType createKillRateEntityListType() {
        return new KillRateEntityListType();
    }

    /**
     * Create an instance of {@link PricingParentType }
     * 
     */
    public PricingParentType createPricingParentType() {
        return new PricingParentType();
    }

    /**
     * Create an instance of {@link ICDListType }
     * 
     */
    public ICDListType createICDListType() {
        return new ICDListType();
    }

    /**
     * Create an instance of {@link RateOfferSettingsType }
     * 
     */
    public RateOfferSettingsType createRateOfferSettingsType() {
        return new RateOfferSettingsType();
    }

    /**
     * Create an instance of {@link BTRatesRequest }
     * 
     */
    public BTRatesRequest createBTRatesRequest() {
        return new BTRatesRequest();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link PricingResponseListType }
     * 
     */
    public PricingResponseListType createPricingResponseListType() {
        return new PricingResponseListType();
    }

    /**
     * Create an instance of {@link ErrorList }
     * 
     */
    public ErrorList createErrorList() {
        return new ErrorList();
    }

    /**
     * Create an instance of {@link UnknownRateEntityIdType }
     * 
     */
    public UnknownRateEntityIdType createUnknownRateEntityIdType() {
        return new UnknownRateEntityIdType();
    }

    /**
     * Create an instance of {@link RateEntityListType }
     * 
     */
    public RateEntityListType createRateEntityListType() {
        return new RateEntityListType();
    }

    /**
     * Create an instance of {@link BTPublishRequest }
     * 
     */
    public BTPublishRequest createBTPublishRequest() {
        return new BTPublishRequest();
    }

    /**
     * Create an instance of {@link PropertyCodeListType }
     * 
     */
    public PropertyCodeListType createPropertyCodeListType() {
        return new PropertyCodeListType();
    }

    /**
     * Create an instance of {@link AvailabilityResponseList }
     * 
     */
    public AvailabilityResponseList createAvailabilityResponseList() {
        return new AvailabilityResponseList();
    }

    /**
     * Create an instance of {@link RelinquishRateEntityListType }
     * 
     */
    public RelinquishRateEntityListType createRelinquishRateEntityListType() {
        return new RelinquishRateEntityListType();
    }

    /**
     * Create an instance of {@link BtPricingRuleType }
     * 
     */
    public BtPricingRuleType createBtPricingRuleType() {
        return new BtPricingRuleType();
    }

    /**
     * Create an instance of {@link RateProgramBTTransactionIDListType }
     * 
     */
    public RateProgramBTTransactionIDListType createRateProgramBTTransactionIDListType() {
        return new RateProgramBTTransactionIDListType();
    }

    /**
     * Create an instance of {@link RateEntityType }
     * 
     */
    public RateEntityType createRateEntityType() {
        return new RateEntityType();
    }

    /**
     * Create an instance of {@link BTRatesStatusRequest }
     * 
     */
    public BTRatesStatusRequest createBTRatesStatusRequest() {
        return new BTRatesStatusRequest();
    }

    /**
     * Create an instance of {@link KnownRateEntityIdType }
     * 
     */
    public KnownRateEntityIdType createKnownRateEntityIdType() {
        return new KnownRateEntityIdType();
    }

    /**
     * Create an instance of {@link AdjustmentRuleType }
     * 
     */
    public AdjustmentRuleType createAdjustmentRuleType() {
        return new AdjustmentRuleType();
    }

    /**
     * Create an instance of {@link ICDType }
     * 
     */
    public ICDType createICDType() {
        return new ICDType();
    }

    /**
     * Create an instance of {@link MirrorAvailabilityListType }
     * 
     */
    public MirrorAvailabilityListType createMirrorAvailabilityListType() {
        return new MirrorAvailabilityListType();
    }

}
