//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParentRateOfferResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParentRateOfferResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParentRateOfferId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ParentRateOfferName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ParentRateEntityId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ParentRateEntityRateProgram" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParentRateOfferResponseType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "parentRateOfferId",
    "parentRateOfferName",
    "parentRateEntityId",
    "parentRateEntityRateProgram"
})
public class ParentRateOfferResponseType {

    @XmlElement(name = "ParentRateOfferId")
    protected long parentRateOfferId;
    @XmlElement(name = "ParentRateOfferName", required = true)
    protected String parentRateOfferName;
    @XmlElement(name = "ParentRateEntityId")
    protected long parentRateEntityId;
    @XmlElement(name = "ParentRateEntityRateProgram", required = true)
    protected String parentRateEntityRateProgram;

    /**
     * Gets the value of the parentRateOfferId property.
     * 
     */
    public long getParentRateOfferId() {
        return parentRateOfferId;
    }

    /**
     * Sets the value of the parentRateOfferId property.
     * 
     */
    public void setParentRateOfferId(long value) {
        this.parentRateOfferId = value;
    }

    /**
     * Gets the value of the parentRateOfferName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentRateOfferName() {
        return parentRateOfferName;
    }

    /**
     * Sets the value of the parentRateOfferName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentRateOfferName(String value) {
        this.parentRateOfferName = value;
    }

    /**
     * Gets the value of the parentRateEntityId property.
     * 
     */
    public long getParentRateEntityId() {
        return parentRateEntityId;
    }

    /**
     * Sets the value of the parentRateEntityId property.
     * 
     */
    public void setParentRateEntityId(long value) {
        this.parentRateEntityId = value;
    }

    /**
     * Gets the value of the parentRateEntityRateProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentRateEntityRateProgram() {
        return parentRateEntityRateProgram;
    }

    /**
     * Sets the value of the parentRateEntityRateProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentRateEntityRateProgram(String value) {
        this.parentRateEntityRateProgram = value;
    }

}
