//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PricingRuleListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricingRuleListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PricingRule" type="{http://com/marriott/rma/webservice/btrates}btPricingRuleType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricingRuleListType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "pricingRule"
})
public class PricingRuleListType {

    @XmlElement(name = "PricingRule", required = true)
    protected List<BtPricingRuleType> pricingRule;

    /**
     * Gets the value of the pricingRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pricingRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPricingRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BtPricingRuleType }
     * 
     * 
     */
    public List<BtPricingRuleType> getPricingRule() {
        if (pricingRule == null) {
            pricingRule = new ArrayList<BtPricingRuleType>();
        }
        return this.pricingRule;
    }

}
