//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PricingResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricingResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateRange" type="{http://com/marriott/rma/webservice/btrates}DateRangeType"/>
 *         &lt;element name="PricingParent" type="{http://com/marriott/rma/webservice/btrates}ParentRateOfferResponseType" minOccurs="0"/>
 *         &lt;element name="CeilingParent" type="{http://com/marriott/rma/webservice/btrates}ParentRateOfferResponseType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricingResponseType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "dateRange",
    "pricingParent",
    "ceilingParent"
})
public class PricingResponseType {

    @XmlElement(name = "DateRange", required = true)
    protected DateRangeType dateRange;
    @XmlElement(name = "PricingParent")
    protected ParentRateOfferResponseType pricingParent;
    @XmlElement(name = "CeilingParent")
    protected ParentRateOfferResponseType ceilingParent;

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeType }
     *     
     */
    public DateRangeType getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeType }
     *     
     */
    public void setDateRange(DateRangeType value) {
        this.dateRange = value;
    }

    /**
     * Gets the value of the pricingParent property.
     * 
     * @return
     *     possible object is
     *     {@link ParentRateOfferResponseType }
     *     
     */
    public ParentRateOfferResponseType getPricingParent() {
        return pricingParent;
    }

    /**
     * Sets the value of the pricingParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentRateOfferResponseType }
     *     
     */
    public void setPricingParent(ParentRateOfferResponseType value) {
        this.pricingParent = value;
    }

    /**
     * Gets the value of the ceilingParent property.
     * 
     * @return
     *     possible object is
     *     {@link ParentRateOfferResponseType }
     *     
     */
    public ParentRateOfferResponseType getCeilingParent() {
        return ceilingParent;
    }

    /**
     * Sets the value of the ceilingParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentRateOfferResponseType }
     *     
     */
    public void setCeilingParent(ParentRateOfferResponseType value) {
        this.ceilingParent = value;
    }

}
