//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyCodeListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyCodeListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PropertyId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="RateProgramBTTransactionIDList" type="{http://com/marriott/rma/webservice/btrates}RateProgramBTTransactionIDListType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyCodeListType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "propertyId",
    "rateProgramBTTransactionIDList"
})
public class PropertyCodeListType {

    @XmlElement(name = "PropertyId")
    protected long propertyId;
    @XmlElement(name = "RateProgramBTTransactionIDList", required = true)
    protected List<RateProgramBTTransactionIDListType> rateProgramBTTransactionIDList;

    /**
     * Gets the value of the propertyId property.
     * 
     */
    public long getPropertyId() {
        return propertyId;
    }

    /**
     * Sets the value of the propertyId property.
     * 
     */
    public void setPropertyId(long value) {
        this.propertyId = value;
    }

    /**
     * Gets the value of the rateProgramBTTransactionIDList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rateProgramBTTransactionIDList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRateProgramBTTransactionIDList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateProgramBTTransactionIDListType }
     * 
     * 
     */
    public List<RateProgramBTTransactionIDListType> getRateProgramBTTransactionIDList() {
        if (rateProgramBTTransactionIDList == null) {
            rateProgramBTTransactionIDList = new ArrayList<RateProgramBTTransactionIDListType>();
        }
        return this.rateProgramBTTransactionIDList;
    }

}
