//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RateEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TransactionDateRange" type="{http://com/marriott/rma/webservice/btrates}DateRangeType"/>
 *         &lt;element name="RateOfferId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="RateProgram" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PropertyRateEntityId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DistanceToLocalOfficeUnit" type="{http://com/marriott/rma/webservice/btrates}DistanceType" minOccurs="0"/>
 *         &lt;element name="DistanceToLocalOffice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="BlackoutDatesList" type="{http://com/marriott/rma/webservice/btrates}ICDListType" minOccurs="0"/>
 *         &lt;element name="CancellationTime" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="LRAFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="YearMinusYFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AttributesInfo" type="{http://com/marriott/rma/webservice/btrates}AttributesType"/>
 *         &lt;element name="AvailabilityList" type="{http://com/marriott/rma/webservice/btrates}MirrorAvailabilityListType" minOccurs="0"/>
 *         &lt;element name="CapsAndRestrictionsInfo" type="{http://com/marriott/rma/webservice/btrates}MirroringType" minOccurs="0"/>
 *         &lt;element name="PricingRuleList" type="{http://com/marriott/rma/webservice/btrates}PricingRuleListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateEntityType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "transactionId",
    "currencyCode",
    "transactionDateRange",
    "rateOfferId",
    "rateProgram",
    "propertyRateEntityId",
    "productCode",
    "accountName",
    "distanceToLocalOfficeUnit",
    "distanceToLocalOffice",
    "blackoutDatesList",
    "cancellationTime",
    "lraFlag",
    "yearMinusYFlag",
    "attributesInfo",
    "availabilityList",
    "capsAndRestrictionsInfo",
    "pricingRuleList"
})
public class RateEntityType {

    @XmlElement(name = "TransactionId")
    protected long transactionId;
    @XmlElement(name = "CurrencyCode", required = true)
    protected String currencyCode;
    @XmlElement(name = "TransactionDateRange", required = true)
    protected DateRangeType transactionDateRange;
    @XmlElement(name = "RateOfferId")
    protected long rateOfferId;
    @XmlElement(name = "RateProgram", required = true)
    protected String rateProgram;
    @XmlElement(name = "PropertyRateEntityId")
    protected Long propertyRateEntityId;
    @XmlElement(name = "ProductCode", required = true)
    protected String productCode;
    @XmlElement(name = "AccountName", required = true)
    protected String accountName;
    @XmlElement(name = "DistanceToLocalOfficeUnit")
    protected DistanceType distanceToLocalOfficeUnit;
    @XmlElement(name = "DistanceToLocalOffice")
    protected BigDecimal distanceToLocalOffice;
    @XmlElement(name = "BlackoutDatesList")
    protected ICDListType blackoutDatesList;
    @XmlElement(name = "CancellationTime")
    protected Short cancellationTime;
    @XmlElement(name = "LRAFlag")
    protected boolean lraFlag;
    @XmlElement(name = "YearMinusYFlag")
    protected Boolean yearMinusYFlag;
    @XmlElement(name = "AttributesInfo", required = true)
    protected AttributesType attributesInfo;
    @XmlElement(name = "AvailabilityList")
    protected MirrorAvailabilityListType availabilityList;
    @XmlElement(name = "CapsAndRestrictionsInfo")
    protected MirroringType capsAndRestrictionsInfo;
    @XmlElement(name = "PricingRuleList", required = true)
    protected PricingRuleListType pricingRuleList;

    /**
     * Gets the value of the transactionId property.
     * 
     */
    public long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     */
    public void setTransactionId(long value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the transactionDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeType }
     *     
     */
    public DateRangeType getTransactionDateRange() {
        return transactionDateRange;
    }

    /**
     * Sets the value of the transactionDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeType }
     *     
     */
    public void setTransactionDateRange(DateRangeType value) {
        this.transactionDateRange = value;
    }

    /**
     * Gets the value of the rateOfferId property.
     * 
     */
    public long getRateOfferId() {
        return rateOfferId;
    }

    /**
     * Sets the value of the rateOfferId property.
     * 
     */
    public void setRateOfferId(long value) {
        this.rateOfferId = value;
    }

    /**
     * Gets the value of the rateProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateProgram() {
        return rateProgram;
    }

    /**
     * Sets the value of the rateProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateProgram(String value) {
        this.rateProgram = value;
    }

    /**
     * Gets the value of the propertyRateEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPropertyRateEntityId() {
        return propertyRateEntityId;
    }

    /**
     * Sets the value of the propertyRateEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPropertyRateEntityId(Long value) {
        this.propertyRateEntityId = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the distanceToLocalOfficeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceType }
     *     
     */
    public DistanceType getDistanceToLocalOfficeUnit() {
        return distanceToLocalOfficeUnit;
    }

    /**
     * Sets the value of the distanceToLocalOfficeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceType }
     *     
     */
    public void setDistanceToLocalOfficeUnit(DistanceType value) {
        this.distanceToLocalOfficeUnit = value;
    }

    /**
     * Gets the value of the distanceToLocalOffice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistanceToLocalOffice() {
        return distanceToLocalOffice;
    }

    /**
     * Sets the value of the distanceToLocalOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistanceToLocalOffice(BigDecimal value) {
        this.distanceToLocalOffice = value;
    }

    /**
     * Gets the value of the blackoutDatesList property.
     * 
     * @return
     *     possible object is
     *     {@link ICDListType }
     *     
     */
    public ICDListType getBlackoutDatesList() {
        return blackoutDatesList;
    }

    /**
     * Sets the value of the blackoutDatesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ICDListType }
     *     
     */
    public void setBlackoutDatesList(ICDListType value) {
        this.blackoutDatesList = value;
    }

    /**
     * Gets the value of the lraFlag property.
     * 
     */
    public boolean isLRAFlag() {
        return lraFlag;
    }

    /**
     * Sets the value of the lraFlag property.
     * 
     */
    public void setLRAFlag(boolean value) {
        this.lraFlag = value;
    }

    /**
     * Gets the value of the cancellationTime property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCancellationTime() {
        return cancellationTime;
    }

    /**
     * Sets the value of the cancellationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCancellationTime(Short value) {
        this.cancellationTime = value;
    }

    /**
     * Gets the value of the yearMinusYFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isYearMinusYFlag() {
        return yearMinusYFlag;
    }

    /**
     * Sets the value of the yearMinusYFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setYearMinusYFlag(Boolean value) {
        this.yearMinusYFlag = value;
    }

    /**
     * Gets the value of the attributesInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getAttributesInfo() {
        return attributesInfo;
    }

    /**
     * Sets the value of the attributesInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setAttributesInfo(AttributesType value) {
        this.attributesInfo = value;
    }

    /**
     * Gets the value of the availabilityList property.
     * 
     * @return
     *     possible object is
     *     {@link MirrorAvailabilityListType }
     *     
     */
    public MirrorAvailabilityListType getAvailabilityList() {
        return availabilityList;
    }

    /**
     * Sets the value of the availabilityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MirrorAvailabilityListType }
     *     
     */
    public void setAvailabilityList(MirrorAvailabilityListType value) {
        this.availabilityList = value;
    }

    /**
     * Gets the value of the capsAndRestrictionsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MirroringType }
     *     
     */
    public MirroringType getCapsAndRestrictionsInfo() {
        return capsAndRestrictionsInfo;
    }

    /**
     * Sets the value of the capsAndRestrictionsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MirroringType }
     *     
     */
    public void setCapsAndRestrictionsInfo(MirroringType value) {
        this.capsAndRestrictionsInfo = value;
    }

    /**
     * Gets the value of the pricingRuleList property.
     * 
     * @return
     *     possible object is
     *     {@link PricingRuleListType }
     *     
     */
    public PricingRuleListType getPricingRuleList() {
        return pricingRuleList;
    }

    /**
     * Sets the value of the pricingRuleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingRuleListType }
     *     
     */
    public void setPricingRuleList(PricingRuleListType value) {
        this.pricingRuleList = value;
    }

}
