//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RateProgramBTTransactionIDListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateProgramBTTransactionIDListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RateProgram" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BTTransactionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateProgramBTTransactionIDListType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "rateProgram",
    "btTransactionId"
})
public class RateProgramBTTransactionIDListType {

    @XmlElement(name = "RateProgram", required = true)
    protected String rateProgram;
    @XmlElement(name = "BTTransactionId")
    protected long btTransactionId;

    /**
     * Gets the value of the rateProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateProgram() {
        return rateProgram;
    }

    /**
     * Sets the value of the rateProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateProgram(String value) {
        this.rateProgram = value;
    }

    /**
     * Gets the value of the btTransactionId property.
     * 
     */
    public long getBTTransactionId() {
        return btTransactionId;
    }

    /**
     * Sets the value of the btTransactionId property.
     * 
     */
    public void setBTTransactionId(long value) {
        this.btTransactionId = value;
    }

}
