//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelinquishRateEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelinquishRateEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="RateOfferId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;choice>
 *           &lt;element name="PropertyRateEntityId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *           &lt;element name="RateProgramCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *         &lt;element name="DateRange" type="{http://com/marriott/rma/webservice/btrates}DateRangeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelinquishRateEntityType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "transactionId",
    "rateOfferId",
    "propertyRateEntityId",
    "rateProgramCode",
    "dateRange"
})
public class RelinquishRateEntityType {

    @XmlElement(name = "TransactionId")
    protected long transactionId;
    @XmlElement(name = "RateOfferId")
    protected long rateOfferId;
    @XmlElement(name = "PropertyRateEntityId")
    protected Long propertyRateEntityId;
    @XmlElement(name = "RateProgramCode")
    protected String rateProgramCode;
    @XmlElement(name = "DateRange")
    protected DateRangeType dateRange;

    /**
     * Gets the value of the transactionId property.
     * 
     */
    public long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     */
    public void setTransactionId(long value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the rateOfferId property.
     * 
     */
    public long getRateOfferId() {
        return rateOfferId;
    }

    /**
     * Sets the value of the rateOfferId property.
     * 
     */
    public void setRateOfferId(long value) {
        this.rateOfferId = value;
    }

    /**
     * Gets the value of the propertyRateEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPropertyRateEntityId() {
        return propertyRateEntityId;
    }

    /**
     * Sets the value of the propertyRateEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPropertyRateEntityId(Long value) {
        this.propertyRateEntityId = value;
    }

    /**
     * Gets the value of the rateProgramCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateProgramCode() {
        return rateProgramCode;
    }

    /**
     * Sets the value of the rateProgramCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateProgramCode(String value) {
        this.rateProgramCode = value;
    }

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeType }
     *     
     */
    public DateRangeType getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeType }
     *     
     */
    public void setDateRange(DateRangeType value) {
        this.dateRange = value;
    }

}
