//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelinquishRateEntityListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelinquishRateEntityListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RelinquishRateEntity" type="{http://com/marriott/rma/webservice/btrates}RelinquishRateEntityType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelinquishRateEntityListType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "relinquishRateEntity"
})
public class RelinquishRateEntityListType {

    @XmlElement(name = "RelinquishRateEntity", required = true)
    protected List<RelinquishRateEntityType> relinquishRateEntity;

    /**
     * Gets the value of the relinquishRateEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relinquishRateEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelinquishRateEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelinquishRateEntityType }
     * 
     * 
     */
    public List<RelinquishRateEntityType> getRelinquishRateEntity() {
        if (relinquishRateEntity == null) {
            relinquishRateEntity = new ArrayList<RelinquishRateEntityType>();
        }
        return this.relinquishRateEntity;
    }

}
