//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.marriott.rfp.webservice.hpp.btrates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnknownRateEntityIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnknownRateEntityIdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MirrorRateOfferId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="PriorityTag" type="{http://com/marriott/rma/webservice/btrates}PriorityTagType"/>
 *         &lt;element name="PricingType" type="{http://com/marriott/rma/webservice/btrates}PricingType"/>
 *         &lt;element name="RoomPoolCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnknownRateEntityIdType", namespace = "http://com/marriott/rma/webservice/btrates", propOrder = {
    "mirrorRateOfferId",
    "priorityTag",
    "pricingType",
    "roomPoolCode"
})
public class UnknownRateEntityIdType {

    @XmlElement(name = "MirrorRateOfferId")
    protected long mirrorRateOfferId;
    @XmlElement(name = "PriorityTag")
    protected long priorityTag;
    @XmlElement(name = "PricingType")
    protected long pricingType;
    @XmlElement(name = "RoomPoolCode", required = true)
    protected String roomPoolCode;

    /**
     * Gets the value of the mirrorRateOfferId property.
     * 
     */
    public long getMirrorRateOfferId() {
        return mirrorRateOfferId;
    }

    /**
     * Sets the value of the mirrorRateOfferId property.
     * 
     */
    public void setMirrorRateOfferId(long value) {
        this.mirrorRateOfferId = value;
    }

    /**
     * Gets the value of the priorityTag property.
     * 
     */
    public long getPriorityTag() {
        return priorityTag;
    }

    /**
     * Sets the value of the priorityTag property.
     * 
     */
    public void setPriorityTag(long value) {
        this.priorityTag = value;
    }

    /**
     * Gets the value of the pricingType property.
     * 
     */
    public long getPricingType() {
        return pricingType;
    }

    /**
     * Sets the value of the pricingType property.
     * 
     */
    public void setPricingType(long value) {
        this.pricingType = value;
    }

    /**
     * Gets the value of the roomPoolCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomPoolCode() {
        return roomPoolCode;
    }

    /**
     * Sets the value of the roomPoolCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomPoolCode(String value) {
        this.roomPoolCode = value;
    }

}
