const Settings = {
  api: {
    getAccSpecQuestions: "/accountquestionmaintedit/getAccSpecQuestions.action",
    updateQuestions: "/accountquestionmaintedit/update.action",
    deleteQuestions: "/accountquestionmaintedit/delete.action",
    getAccQuestionTypes: "/accountquestiontype/getAccQuestionTypes.action",
    getCustomAns: "/accountquestiontype/getCustomAns.action",
    fetchAnswered: "/accountquestiontype/fetchAnswered.action",
    downloadTemplate: "/accountquestionmaintedit/download.action",
    importExcelData: "/accountquestionmaintedit/importExcelData.action",
  },

  questionType: {
    keyField: "typeid",
    valField: "typedescription",
    id: "typeid",
  },

  blankQueList: [
    {
      question_id: 0,
      question_seq: 1,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_id: 0,
      question_seq: 2,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_id: 0,
      question_seq: 3,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_id: 0,
      question_seq: 4,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 5,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 6,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 7,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 8,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 9,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 10,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 11,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 12,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 13,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 14,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 15,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 16,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 17,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 18,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 19,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 20,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 21,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 22,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 23,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 24,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 25,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 26,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 27,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 28,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 29,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
    {
      question_seq: 30,
      question_id: 0,
      question: "",
      edie_column_label: "",
      typedescription: "Free Form",
      typeid: "1",
      hasrecs: "N",
      max_len: null,
      customAnswers: null,
      ansEdited: null,
    },
  ],

  Questions: {
    yes: "Y",
    customAns: "Custom Answers",
    editLabel: "Edit",
    deleteImgAltText: "Delete Question.",
    exportImgAlt: "Export Template",
    importImgAlt: "Import Questions",
    ansExistsImgAltText: "Answer exists for the question.",
    questionTypeLabel: "Question Type:",
    fileName: "Template_Addendum_Questions",
    ansLabel: "Answer",
    strHasrecs: "hasrecs",
    strCustomAnswers: "customAnswers",
    stransEdited: "ansEdited",
    strtypedescription: "typedescription",
    isImportButtonClicked: "isImportButtonClicked",
    isDataTypeClicked: "isDataTypeClicked",
    isEditClicked: "isEditClicked",
    maxLength: 400,
    maxcharAlertMesaage: "You are allowed to enter up to 400 characters.",
    tableColumns: {
      id: {
        field: "question_id",
      },
      answersExist: {
        field: "infoanswersexist",
        header: "Answers Exist",
      },
      questNo: {
        field: "question_seq",
        header: "Quest. No.",
      },
      question: {
        field: "question",
        header: "Question",
      },
      edieExcelLabel: {
        field: "edie_column_label",
        header: "EDIE Excel Label",
      },
      answerLength: {
        field: "max_len",
        header: "Answer Length",
      },
      dataType: {
        field: "typedescription",
        header: "Data Type",
      },
    },
  },
  questionTypes: {
    title: "Question Types",
    quesLabel: "Question Types",
  },
  answerList: {
    title: "Enter Custom Answers",
    quesLabel: "Answer",
    id: "customAnswers",
  },
};
export default Settings;
