const Settings = {
  api: {
    getReports: "/generalreportnofilterlist/getReportNoFilterViewLists",
    getData: "/pricingreportnofilterlist/getReportNoFilterViewLists.action",
    runReport: "/generalreportnofilterlist/runReport",
    getCognosUrl: "/reports/getAppEnvDetails.action",
  },
  header: "General Administration : Request Special Reports",
  label: {
    report: "Report:",
    year: "Year:",
    account: "Account:",
    marshaCode: "Marsha Code:",
    email: "Email me when report is ready",
    eid: "EID:",
    role: "Role:",
  },
  sortBy: [
    {
      id: "",
      name: "*",
    },
    {
      id: "eHotelAccountAccess",
      name: "Access by Hotel and/or Account (Excel)",
    },
    {
      id: "eUsers",
      name: "User List Electronic",
    },
  ],
  recorddropdown: {
    id: "report_name",
    name: "report_name",
    id_year: "period",
    name_year: "period",
  },
  ControlKeyValues: {
    cSelectKeyField: "report_name",
    cSelectValueField: "report_title",
  },
  blankReport: {
    report_name: 0,
    report_title: "*",
    is_electronic: null,
    allow_accounttype: null,
    allow_account: null,
    allow_period: null,
    add_params: null,
    req_account: null,
    req_roles: null,
    allow_region: null,
    allow_proximitysubcat: null,
    schedule_time: null,
    priority: null,
    req_acct_or_region: null,
    req_daterange: null,
    fsale_all_hotels: null,
    allow_account_eligible: null,
    allow_quarter: null,
    acctplan_options: null,
    sale_all_account: null,
    allow_saleslist: null,
    allow_apadminview: null,
    allow_account_solicited: null,
    include_marriott_contact: null,
    allow_onehotel: null,
    allow_eid: null,
    allow_futureopenings: null,
    allow_dateformat: null,
    req_acct_region_brand: null,
    allow_schedule: null,
    allow_cbchotels: null,
    allow_pgoosStatus: null,
    amenity_count: null,
  },
};

export default Settings;
